### ISSUE TITLE
Hi, i try to use docker to start testlink that connect to an exists database which table has tl_ prefix. what env variable should  use when i run docker? Or where can i check all supported ENV variables?thanks. 

### ISSUE THREAD

**Issue by liijuun** [bitnami/bitnami-docker-testlink#101]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by jotamartos** [comment]
Hi @liijuun ,

Thank you for your interest. Our solution doesn't support to specify a table prefix when launching the container. You can get all the env variables you can use when launching the docker image here:

https://github.com/bitnami/bitnami-docker-testlink#environment-variables

In case you want to use the solution, you will need to launch it and configure it by your own. Once you modify the app's configuration, you will need to restart the container for the changes to take effect. 

I hope this helps

**Comment by liijuun** [comment]
Hi @jotamartos ,

Thanks for your help. 

i try to start container with below command:
docker run -d --name testlink -p 80:80 -p 443:443  -e MARIADB_HOST=xxxx -e TESTLINK_DATABASE_USER=root -e TESTLINK_DATABASE_PASSWOR D=root123 -e TESTLINK_DATABASE_NAME=lijun_test -e TESTLINK_USERNAME=admin -e TESTLINK_PASSWORD=admin bitnami/testlink:1.9.19

when i open web page, it shows login page directly, and there is no configuration for DB.

Is there any configuration file i need to update in container filesystem? Could you please guide me? 
Thanks very much.

**Comment by jotamartos** [comment]
>Is there any configuration file i need to update in container filesystem? Could you please guide me?

As I mentioned, there is no way to configure the table prefix to use when launching the container. You can launch the application with the parameters you specified and then edit its configuration file (inside the /opt/bitnami/testlink folder) using the container's command line 

```
docker exec -it testlink bash
```

You will need to use a command line editor to update that parameter. This scenario has not been tested so I don't know if the application will work properly after making the change.

Thanks

**Comment by liijuun** [comment]
Ok, Thanks.
