### ISSUE TITLE
Array in HTML Code obstructing the page

### ISSUE THREAD

**Issue by gforke97** [bitnami/bitnami-docker-testlink#102]
If you select a "folder" in the "Assign Test Case Execution" Page an Array with alot of testcase id's is shown.

HTML Code:
```
<pre>
array(5) {
 ["keywords"]=&gt;
 int(0)
 ["testcases"]=&gt;
 array(569) {
 ommited
	}
 ["exec_type"]=&gt;
 NULL
 ["cfields"]=&gt;
 NULL
 ["platforms"]=&gt;
 int(0)
}
</pre>
```

**Steps to reproduce the issue:**

1. Switch to the "Assign Test Case Execution" Page
2. Select a "folder" with tests

**Describe the results you received:**
![grafik](https://user-images.githubusercontent.com/19305191/86222065-03ae7c80-bb86-11ea-99f8-c0173c744b9c.png)

I expect a normal view without an Array obstructing the page.

**Version**

- Output of `docker version`:

Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:22:03 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:20:35 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

- Output of `docker info`:

Client:
 Debug Mode: false

Server:
 Containers: 26
  Running: 21
  Paused: 0
  Stopped: 5
 Images: 37
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.0-9-amd64
 Operating System: Debian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.42GiB
 Name: hb-rz-dkr-001
 ID: NU5L:YBNC:ROST:IWTP:EJ6B:3C6V:U2D2:MIMC:JK46:T7QS:IC7U:54KI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

- Output of `docker-compose version` (if applicable):

docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi @gforke97,
  Do you have errors in the containers ? 
  At first sight, it seems to be a bug in testlink, in that case I would suggest you to use testlink's forums.

**Comment by gforke97** [comment]
I made an Issue in the testlink forum now.
http://mantis.testlink.org/view.php?id=8954

**Comment by gforke97** [comment]
I opened an Issue in the Testlink Forum now.
http://mantis.testlink.org/view.php?id=8954

**Comment by rafariossaa** [comment]
@gforke97  
Thanks, please don't hesitate to come back a and post your findings.

**Comment by gforke97** [comment]
@rafariossaa the problem was fixxed in the github branch testlink_1_9_20_fixed (https://github.com/TestLinkOpenSourceTRMS/testlink-code/tree/testlink_1_9_20_fixed) which isnt expected to be merged until november.

http://mantis.testlink.org/view.php?id=8954

**Comment by rafariossaa** [comment]
Hi @gforke97,
  Thank you very much for sharing your findings. 
  Unfortunately we can not use specific commits or branches, and need to wait until they make a release with the fixes.
