### ISSUE TITLE
Testlink under a different location route path

### ISSUE THREAD

**Issue by amruthapbhat** [bitnami/bitnami-docker-testlink#103]
Hi,

Is there anyway where we can run testlink docker container under /testlink path rather than the / path. Is there any env variable that can be used to achieve this as I have some other applications running under the / path

**Comment by joancafom** [comment]
Hi @amruthapbhat ,

This image supports the addition of custom `VirtualHosts` and/or `httpd.conf` files (see the [extending this image](https://github.com/bitnami/bitnami-docker-testlink#extend-this-image) section). You said you have some other applications running under the root path, could you provide me with a little bit more context? Maybe it would be a better idea to use a reverse proxy to serve all the applications 😄.

Thanks!

**Comment by amruthapbhat** [comment]
Hi @joancafom,

I have a k8s platform where in a have couple of application running. The applications are running under the same fqdn but under different routes for ex: fqdn/application1 and fqdn/application2. Now my scenario is i want to run testlink under the same fqdn and under it as fqdn/testlink.

**Comment by joancafom** [comment]
Hi @amruthapbhat,

Oh, I see, thank you. I have found that some user had a similar issue #54 Could you please tell me if that solution works for you? 

Thanks!
