### ISSUE TITLE
manitis

### ISSUE THREAD

**Issue by alexfu168** [bitnami/bitnami-docker-testlink#104]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi @alexfu168 ,
  Could you describe your issue, steps to reproduce it, etc ?

**Comment by rafariossaa** [comment]
Hi, 
  I am closing this issue due to the lack of information.
  Please don't hesitate to open a new issue with all the information that may help to solve your issue.
