### ISSUE TITLE
Use .pem certificates in apache

### ISSUE THREAD

**Issue by luizbob** [bitnami/bitnami-docker-testlink#105]
I think you guys if possible can change the way to use certificates in this docker, using crt and key only do not allow to use let's encrypt certificates out of the box

**Comment by marcosbc** [comment]
@luizbob Just rename the pem files to server.crt (certificate) and server.key (private key) and it should work, following these steps: https://github.com/bitnami/bitnami-docker-apache#using-custom-ssl-certificates

Note you could always mount the certificates like this:

```
    volumes:
      - /etc/letsencrypt/live/mydomain.com/key.pem:/certs/server.key
      - /etc/letsencrypt/live/mydomain.com/cert.pem:/certs/server.crt
```

If you find any error, let us know.
