### ISSUE TITLE
New TestLink version detection should get max version from db_version

### ISSUE THREAD

**Issue by hokor** [bitnami/bitnami-docker-testlink#106]
**Description**

Get a Duplicate PRIMARY error when run  bitnami/testlink:1.9.20 with a existing DB 
```
Error executing 'postInstallation': MySQL command failed to run. Error:
 ERROR 1062 (23000) at line 2: Duplicate entry '47' for key 'PRIMARY'
```
I checked the trace log and  found the New TestLink version detection sql get all versions.
```
mysql-c TRACE [execute] Executing: mysql -N -P 3306 -htestklindb -Dtestlink -utestlink  -ptestlink  -e SELECT version FROM db_version;
mysql-c TRACE [execute] Result: {"code":0,"stdout":"DB 1.9.14\nDB 1.9.15\nDB 1.9.16\nDB 1.9.17\nDB 1.9.18\nDB 1.9.19","stderr":""}
testlin INFO  New TestLink version detected
testlin INFO  Patch version detected, starting upgrade process...
testlin DEBUG Executing "/opt/bitnami/testlink/install/sql/alter_tables/1.9.15/mysql/DB.1.9.15/step1/db_schema_update.sql"...
```
It should only get the max version.
```
SELECT max(version) as verison FROM db_version;
```

**Comment by andresbono** [comment]
Thanks for identifying and reporting this issue. We are going to evaluate it and we will get back to you.

**Comment by andresbono** [comment]
It seems like the proposed implementation might cause issues because `max` sorts ignoring natural order. that means `1.9.20` < `1.9.3`.

What do you think about this other query? It orders the versions by the upgrade timestamp and takes the latest.

```
SELECT version FROM db_version ORDER BY upgrade_ts DESC LIMIT 1;
```

**Comment by andresbono** [comment]
We will go ahead with the implementation using order by date.

**Comment by andresbono** [comment]
Hi again, please check the release `1.9.20-debian-10-r167` https://github.com/bitnami/bitnami-docker-testlink/commit/861fd0f4eaed8d77e1a4eea478ff621c9071c8c2. It includes the fix to this issue. Could you please let us know if it works for you? Thanks for reporting the issue!
