### ISSUE TITLE
Testlink use smtp aws ses

### ISSUE THREAD

**Issue by abdidarmawan007** [bitnami/bitnami-docker-testlink#107]
How to set env in docker use smtp aws ses
for example i have config aws ses 

SMTP hosts = email-smtp.us-east-1.amazonaws.com
SMTP port = 465
SMTP security = SSL
SMTP username: dew2dqdwdewda
SMTP password: Dejd23djqdj3dqwd
From address: hi@test.com

we need config env for from adress

**Comment by carrodher** [comment]
Hi, you can follow the instructions from the README: https://github.com/bitnami/bitnami-docker-testlink#smtp-configuration
