### ISSUE TITLE
How to change "localhost" in URL to server IP

### ISSUE THREAD

**Issue by jkkuo** [bitnami/bitnami-docker-testlink#109]
While testlink sends out an email notification, it will take "localhost" in the URL link.
But the users in other places can't recognize "localhost", so they will not able to connect to the link.
Is there any configuration allowing us to change the "localhost" in URL to the server IP?

Below is the the email notification sent by Testlink

===========================================
Test Project: Test
Test Plan: Test

You need to be logged in order to use link

http://localhost/ltx.php?item=xta2m&tplan_id=1919&user_id=4

Generated by TestLink on Thu, 29 Oct 2020 02:08:45 +0000 

=============================================

**Comment by andresbono** [comment]
Hi @jkkuo, thanks for opening this issue. I'm not sure how that URL is generated, but it could be related to the this configuration define and its related function, links below.

https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/44f48e97354bc530c9eb272fa767e7ca19c1a710/config.inc.php#L1376

https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/44f48e97354bc530c9eb272fa767e7ca19c1a710/lib/functions/configCheck.php#L29

Can you try overwriting it in your configuration file and let us know if it works? You may want to post this question in the TestLink forums.

If you find a solution, we can try to adapt our container to add support for configuring the URLs.

**Comment by jkkuo** [comment]
Hi andresbono,
Thank for your reply. URL is generated by the function you provided in

https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/44f48e97354bc530c9eb272fa767e7ca19c1a710/lib/functions/configCheck.php#L29

I further search for where "SERVER_NAME" and "SERVER_PORT" is set.
And they are found in:

https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/b3004c6fa1b7cfcb61023b339f95212d706d9a11/third_party/Slim/Environment.php#L95

After changing the SERVER_NAME and SERVER_PORT to the my server's name and port.
The URL sent by testlink is changed successfully.

BTW I found there is a problem while setting SMTP mail server.
I use postfix on my LINUX server as mail server and this kind of mail server doesn't require username and password.
But it seems like if I want to set up the container by the docker-compose file, I have to set username and password for SMTP server. I think the examination mechanism for the existence of SMTP's username and password might cause some problem.

Thanks for your effort again!

**Comment by andresbono** [comment]
It's great that you were able to solve the issue!

About your SMTP scenario, yes, you are right. SMTP user and password are needed right now and we don't support empty values for those. We will revisit the configuration to adapt to your use case.
