### ISSUE TITLE
The search result does not appear in TestLink 1.9.20 [DEV] instead it shows "DB Access Error - debug_print_backtrace() OUTPUT START" 

### ISSUE THREAD

**Issue by shashanknaik1990** [bitnami/bitnami-docker-testlink#110]
**Description**

The search result does not appear in TestLink 1.9.20 [DEV] instead it shows "DB Access Error - debug_print_backtrace() OUTPUT START" 
Here I have installed only BITNAMI TESTLINK STACK without any Xampp server. Everything else is working as TESTLINK STACK itself contains phpMyAdmin for a database with SQL support.

**Steps to reproduce the issue:**

1. Install the Testlink from Bitnami Virtual Appliance. i.e from "https://bitnami.com/stack/testlink/installer"
2. After installation with configuration enter "http://localhost/testlink/login.php" in browser.
3. Add project information.
4. Add any record for searching purpose.
5. To search for a record enter any keyword in "Full text search" field.
6. Press keyboard "Enter" button.

**Actual Result:**

At step 6 I got the following message.

DB Access Error - debug_print_backtrace() OUTPUT START   ATTENTION: Enabling more debug info will produce path disclosure weakness (CWE-200)              Having this additional Information could be useful for reporting              issue to development TEAM.   ==============================================================================  #0  database->exec_query() called at [C:\Bitnami\testlink-1.9.20-8\apps\testlink\htdocs\lib\functions\database.class.php:641] #1  database->fetchRowsIntoMap() called at [C:\Bitnami\testlink-1.9.20-8\apps\testlink\htdocs\lib\search\searchCommands.class.php:781] #2  searchCommands->searchTestSuites() called at [C:\Bitnami\testlink-1.9.20-8\apps\testlink\htdocs\lib\search\search.php:99]

**Expected:**

It should show the related records with the searched keyword.

**Platform**
Windows 10 64-bit
BITNAMI TESTLINK STACK

**Version**
TestLink 1.9.20 [DEV] 

Refer the following screenshot.
![image](https://user-images.githubusercontent.com/61155880/100184837-6a9f4a00-2f08-11eb-8172-c87f49328b0e.png)

(**Note:** If anything needs to be configured from my end then please let me know.)

**Comment by miguelaeh** [comment]
Hi @shashanknaik1990 ,
It seems you are using the installer instead of the Docker image. Have in mind this is the repository is for the Docker image. Please open a new ticket at https://community.bitnami.com/ and our team will be pleased to help you.
Sorry for the inconvenience.
Regards.
