### ISSUE TITLE
Several issues were found on testlink 1.9.20, would you please create a new docker file base on testlink_1_9_20_fixed branch on github.

### ISSUE THREAD

**Issue by shinobi01** [bitnami/bitnami-docker-testlink#111]
**Description**

Several issues were found on testlink 1.9.20, and they should be fixed on testlink_1_9_20_fixed branch.
would you please help to create a new docker file base on this branch?

**Steps to reproduce the issue:**

1. Unable to import customed field via xml.
https://github.com/TestLinkOpenSourceTRMS/testlink-code/commit/4e3253b05fb768d66064ab64b49734e654260320

2. DB error occurs when assigning testers.
https://github.com/TestLinkOpenSourceTRMS/testlink-code/commit/b0c64f3f0daf05ae101ae1c81ddc0de30ff16b27

3. and so on.

**Describe the results you received:**

Those issues are impect for using testlink.

**Describe the results you expected:**

Able to import customed field and no error when assigning test case to testers.

**Additional information you deem important (e.g. issue happens only occasionally):**

Always

**Version**

- Output of `docker version`:
Now i'm using bitnami/testlink:latest and bitnami/mariadb:latest, i don't know how to use testlink_1_9_20_fixed branch to solve the issues.

Thank you very much.

**Comment by juan131** [comment]
Hi @shinobi01 

Thanks so much for reaching us to warn about this.

We track new versions from the "releases" GitHub page below:

- https://github.com/TestLinkOpenSourceTRMS/testlink-code/releases

We understand these are the latest **stable** releases by Testlink, although there can be new commits added on development branches we don't usually track these branches and only ship the stable code. As soon as the upstream project release a new stable version, it'll be automatically detected/packed/released by our pipeline.

**Comment by shinobi01** [comment]
@juan131 
thanks for your feedback. I know there are so many develop/fix/feature branches in github, we can't track them all.
and I noticed that testlink released every year. As their publish frequency, they will release in the last few moth. Maybe i could keep an eye on it. Thank you so much and have a nice day.

**Comment by shinobi01** [comment]
@juan131 
As I know, testlink 1.9.20 will be the last version of 1.9.xx family, and from next version(2.x) they will base on the new UX.
So shell we packed a finial version include those fixs in testlink_1_9_20_fixed branch? thank you very much.

**Comment by juan131** [comment]
Hi @shinobi01 

Thanks for sharing your thoughts!

We'd like to consult this decision with the upstream project maintainers. We'll keep you in the loop!

**Comment by mdkka** [comment]
Hi, yes this is very pity that this branch contains these errors, it was not easy to find out that we should use the testlink_1_9_20_fixed  branch.  
I can confirm that the issues we observe with this docker images are because of that branch because I have installed testlink_1_9_20 branch manually  and got the same issues as with this docker image.  After changing to testlink_1_9_20_fixed  branch it was good.
It would be very nice to switch to testlink_1_9_20_fixed  branch. Sadly the only place where I found the info to switch to fixed branch was on Mantis of Testlink project and here ;)

**Comment by juan131** [comment]
Hi everyone,

We contacted the upstream project maintainers, and they told us there shouldn't be any problem on using the development branch "testlink_1_9_20_fixed" while the `2.x` major version is released. That said, we'll still stick to the latest release available in GitHub.

To use the "fixed" branch version, you can follow these steps:

- Clone the repository and move to the `1/debian-10` directory:

```console
$ git clone https://github.com/bitnami/bitnami-docker-testlink.git
$ cd bitnami-docker-testlink/1/debian-10
```

- Create a "local" directory and download/uncompress the Bitnami Testlink tarball running the command below:

```
$ mkdir local && cd local
$ curl -LO https://downloads.bitnami.com/files/stacksmith/testlink-1.9.20-5-linux-amd64-debian-10.tar.gz
```

- Apply the changes below in the [the Dockerfile](https://github.com/bitnami/bitnami-docker-testlink/blob/master/1/debian-10/Dockerfile), and build your custom image:

```diff
 RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "libphp" "7.3.27-1" --checksum 92d2a0e197d171c0661a66f9e25ae6ca2f91dd6edf1c319b8e152929299c837d
-RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "testlink" "1.9.20-5" --checksum be9e4bf92350efb70026353ac6bf1650e7d472c89ad69ae791723795358d37f0
+COPY /tmp/bitnami/pkg/cache/
+RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "testlink" "1.9.20-5" 
 RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "render-template" "1.0.0-3" --checksum 8179ad1371c9a7d897fe3b1bf53bbe763f94edafef19acad2498dd48b3674efe
```

**Comment by shinobi01** [comment]
@juan131 @mdkka appreciate for your help, it works, thank you very much and have a nice day. Thanks to your teams too.
