### ISSUE TITLE
Value of Custom Field 'xxx' can not be imported because there is no Custom Field with this name and Available for Test Case on this Test Project

### ISSUE THREAD

**Issue by liyinchigithub** [bitnami/bitnami-docker-testlink#115]
![image](https://user-images.githubusercontent.com/19643260/115529615-a1b23580-a2c5-11eb-82f8-723f01693ca7.png)

![image](https://user-images.githubusercontent.com/19643260/115529718-b55d9c00-a2c5-11eb-9a99-649bca39295b.png)

**Comment by alvneiayu** [comment]
hi @liyinchigithub 

I need more information to try to help you.
-  What is the version that you are using in TestLink?
-  What is the steps that you are following to reproduce the issue?
- Could you share with me the files that you are importing? What is the field that you are importing? Custom fields? I am exporting and importing custom fields and I am not having problems.
- Could you share with me the docker compose file that you are using?

Please share with me also docker logs with the error that you are having.

Thanks and I will be looking forward your reply

Álvaro

**Comment by liyinchigithub** [comment]
@alvneiayu 
thank you

version 1.9.20 latest

file xml

[20200710.xml.zip](https://github.com/bitnami/bitnami-docker-testlink/files/6369156/20200710.xml.zip)

**Comment by alvneiayu** [comment]
hi @liyinchigithub 

I did a test file to import testsuite and testcases:

[testfile.zip](https://github.com/bitnami/bitnami-docker-testlink/files/6378156/testfile.zip)

And I can not reproduce any problem importing a testcase. I am not expert in Testlink but it seems that something with the format or the structure of you xml is not ok for Testlink. The docker image is working properly.

Let me know If I can help you with something else.

Álvaro

**Comment by liyinchigithub** [comment]
@alvneiayu 
Thank you very much for your answer
