### ISSUE TITLE
How can we access same url (test link) for other machines ?

### ISSUE THREAD

**Issue by shanmukhkagal** [bitnami/bitnami-docker-testlink#119]
How can we access the same URL (testlink) for other machines?

**Comment by carrodher** [comment]
If you deploy the testlink container via `docker run` [1] or `docker-compose up` [2] as described in the README the application is going to be running at http://YOUR_IP/. Take into account ports are mapped between the container and the host machine: `-p 8080:8080 -p 8443:8443`.

If you want to expose the application outside your local machine you need to properly configure the networking and expose the IP and ports, as it is not an issue related to this image but a generic container question, I recommend you to look for info in specific forums such as the Docker one.

[1] https://github.com/bitnami/bitnami-docker-testlink#using-the-docker-command-line
[2] https://github.com/bitnami/bitnami-docker-testlink#run-the-application-using-docker-compose
