### ISSUE TITLE
Test link getting failed immediately after starting the container

### ISSUE THREAD

**Issue by balajimark** [bitnami/bitnami-docker-testlink#120]
Hi,

I have started setting up the test link docker container by following the below URL

[https://hub.docker.com/r/bitnami/testlink/Test ]

Set up has been completed but test link is getting failed immediately after starting the container.

Initially I faced issue with Maria DB startup due to permission issue and it was fixed. But test link is not.

CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                     PORTS                                              NAMES
3b232da69b45        bitnami/testlink:1     "/opt/bitnami/script…"   About an hour ago   Exited (1) 7 minutes ago                                                      testlink_testlink_1
f2a24e4b2405        bitnami/mariadb:10.3   "/opt/bitnami/script…"   About an hour ago   Up 52 minutes              3306/tcp                                           testlink_mariadb_1

**Please find the container log:**

testlink 14:06:55.81 Welcome to the Bitnami testlink container
testlink 14:06:55.81 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-testlink
testlink 14:06:55.81 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-testlink/issues
testlink 14:06:55.82
testlink 14:06:55.82 INFO  ==> ** Starting TestLink setup **
realpath: /bitnami/apache/conf: No such file or directory
testlink 14:06:55.89 INFO  ==> Configuring PHP options
testlink 14:06:55.90 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
testlink 14:06:55.96 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
testlink 14:06:56.02 INFO  ==> Configuring TestLink with settings provided via environment variables
testlink 14:06:56.06 INFO  ==> Ensuring TestLink directories exist
testlink 14:06:56.06 INFO  ==> Trying to connect to the database server

**docker version:**

Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**docker info:**

Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 4
  Paused: 0
  Stopped: 2
 Images: 8
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1062.12.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.67GiB
 Name: ex-npe-cntr-devops-hybris-new.internal.cloudapp.net
 ID: X2W2:AS4U:DPL5:QCBF:AIXJ:4QEG:ZD7L:NWOP:H66Z:K36S:M5PE:LQXN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**docker-compose version:**

docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

This is hosted in **Azure VM and OS - Linux (centos 7.7.1908)**

Can you please update the cause of this issue and help me in getting this fixed.

Thanks,

**Comment by marcosbc** [comment]
Hi @balajimark, that indicates that your database credentials are not correct. I recommend you to check the [`TESTLINK_DATABASE_*` environment variables](https://github.com/bitnami/bitnami-docker-testlink#use-an-existing-database).

If you continue to find issues, please share the docker-compose.yml/commands so we can further help.

**Comment by mbudim** [comment]
hi, I also find the same issue

**Comment by javsalgar** [comment]
Please, note the Bitnami team is not actively monitoring GitHub Issues for this Helm chart. This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.
If you would like to contribute to this Helm chart by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
