### ISSUE TITLE
local built image are not able to lunch

### ISSUE THREAD

**Issue by yx135790** [bitnami/bitnami-docker-testlink#124]
Hey I was trying to build the image locally from docker file, with nothing changed
while the image are unable to lunch 
error:

`
/opt/bitnami/scripts/testlink/entrypoint.sh: line 11: /opt/bitnami/scripts/testlink-env.sh: Permission denied
`
I have a question ,all files owner is set to something called **daemon**, but daemon is not user 1001
so I have to add this in the dockefile
`RUN chown -R 1001:root /opt/bitnami`

**Comment by carrodher** [comment]
The approach used to convert root containers into non-root is to use a random user that is part of the root group. If you are mounting a local volume you should ensure that the permissions match this approach.

You can find more info in the following doc sites:
- https://engineering.bitnami.com/articles/why-non-root-containers-are-important-for-security.html
- https://docs.bitnami.com/tutorials/work-with-non-root-containers/

**Comment by yx135790** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by yx135790** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
