### ISSUE TITLE
Incorrect password substitution in config_db.inc.php

### ISSUE THREAD

**Issue by Kangie** [bitnami/bitnami-docker-testlink#125]
**Description**

When attempting to setup a new Bitnami Testlink instance to replace a legacy instance I encountered an issue where password substitution failed. It appears that special characters (definitely `&` and `$` and based on my past experience `\` and `/`) are not escaped.

Example output for password `*rz#HbNx3G^7V6$2iAu$D84d9`:

```bash
root@docker.server.hostname:/path/to/testlink# docker exec -it -u root 3d22 /bin/bash
root@3d226bbdc268:/# cd /opt/bitnami/testlink
root@3d226bbdc268:/opt/bitnami/testlink# cat config_db.inc.php 
<?php
define('DB_TYPE', 'mysql');
define('DB_HOST', 'testlink_database:3306');
define('DB_NAME', 'bitnami_testlink');
define('DB_USER', 'bn_testlink');
define('DB_PASS', '*rz#HbNx3G^7V6define('DB_PASS', '');2iAudefine('DB_PASS', '');D84d9');
?>
```
I've resolved a [similar issue for the linuxserver.io bookstack docker container](https://github.com/linuxserver/docker-bookstack/pull/101) where they were not properly substituting variables using `sed`; based on the output this is the same issue though I haven't yet had time to track down where/how this container is generating this file. I suspect `sed` substitution based on the current output, which can be resolved by instead substituting an escaped password using something similar to:

```bash
ESCAPED_PASSWORD=$(sed -e 's/[$\/&]/\\&/g' <<< $DB_PASS)
```

**Steps to reproduce the issue:**

1. Start a new testlink stack/compose file with a complex password containing any combination of the above characters for the `TESTLINK_DATABASE_PASSWORD` variable.
2. Observe the incorrect substitution in the database config (`/opt/bitnami/testlink/config_db.inc.php`).
3. TestLink will fail to communicate with the MariaDB instance with this password set / will constantly choke on container init.

**Describe the results you received:**

TestLink is unable to communicate with the database due to incorrect credentials in the database config.

**Describe the results you expected:**

Complex passwords are accepted and respected with no limitations on characters.

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-testlink#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
