### ISSUE TITLE
Manage custom conf

### ISSUE THREAD

**Issue by bhaku** [bitnami/bitnami-docker-testlink#20]
I need to use LDAP but now i can't manage custom configuration.

Can you add possibility to manage it?

**Comment by juan131** [comment]
The Bitnami php component is compiled with ldap support as you can check with the following command:

```
$ php -i | grep "Configure Command"
```

Also, the apache ldap extensions are located at:

```
/opt/bitnami/apache/modules/mod_ldap.so
/opt/bitnami/apache/modules/mod_authnz_ldap.so.
```

You just need to enable it editing `/opt/bitnami/apache/conf/httpd.conf` by uncommenting the following lines.

```
#LoadModule authnz_ldap_module modules/mod_authnz_ldap.so
#LoadModule ldap_module modules/mod_ldap.so
```

Finally restart your apache server with the following command:

```
$ nami restart apache
```

**Comment by dbarranco** [comment]
I'm proceeding to close this issue since it hasn't got any kind of activity.

Feel free to open it if you find any issue related to this.

Best regards.
