### ISSUE TITLE
 SMTP host not properly configured!

### ISSUE THREAD

**Issue by huiwu** [bitnami/bitnami-docker-testlink#49]
docker-compose.yml
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/home/xxx/testlink/mariadb:/bitnami/mariadb'
  testlink:
    image: 'testlink:1.9.16'
    ports:
      - '4000:80'
      - '4430:443'
    volumes:
      - '/home/xxx/testlink/testlink:/bitnami/testlink'
      - '/home/xxx/testlink/apache:/bitnami/apache'
      - '/home/xxx/testlink/bitnami-php:/bitnami/php'
    depends_on:
      - mariadb

=========================================
config.inc.php

$g_smtp_host        = 'smtp.test.com';  # SMTP server MUST BE configured

# Configure using custom_config.inc.php
$g_tl_admin_email     = 'test@test.com'; # ======
$g_from_email         = 'test@test.com'; # ======
$g_return_path_email  = 'test@test.com'; # ======

/**
 * Email notification priority (low by default)
 * Urgent = 1, Not Urgent = 5, Disable = 0
 **/
$g_mail_priority = 5;

/**
 * Taken from mantis for phpmailer config
 * select the method to mail by:
 * PHPMAILER_METHOD_MAIL - mail()
 * PHPMAILER_METHOD_SENDMAIL - sendmail
 * PHPMAILER_METHOD_SMTP - SMTP
 */
$g_phpMailer_method = PHPMAILER_METHOD_SMTP;

/** Configure only if SMTP server requires authentication */
$g_smtp_username    = 'test@test.com';  # ======
$g_smtp_password    = 'test';  # ======

/**
 * This control the connection mode to SMTP server.
 * Can be '', 'ssl','tls'
 * @global string $g_smtp_connection_mode
 */
$g_smtp_connection_mode = '';

/**
 * The smtp port to use.  The typical SMTP ports are 25 and 587.  The port to use
 * will depend on the SMTP server configuration and hence others may be used.
 * @global int $g_smtp_port
 */
$g_smtp_port = 25;  # ======

**Comment by andresbono** [comment]
Hi @huiwu, you can check the following section of the _README.md_ of this repo: [SMTP Configuration](https://github.com/bitnami/bitnami-docker-testlink#smtp-configuration). There, you can find how to pass environment variables to the testlink container so the container is automatically configured with the smtp options that you want. Is this approach valid for you?

**Comment by huiwu** [comment]
Yes, it is invalid; Modify “custom_config.inc.php” to take effect

**Comment by javsalgar** [comment]
Hi, when you say it is invalid you mean that you tried with that approach and it did not work? Or is there a specific reason why you cannot use the environment variables in the docker compose file?

**Comment by huiwu** [comment]
Yes, I tried using the  environment variables， but it did not take effect, so I can only configure “custom_config.inc.php”

**Comment by andresbono** [comment]
Hi @huiwu,

If you see the `custom_config.inc.php` file (`/opt/bitnami/testlink/custom_config.inc.php`), you will have some empty properties that you will need to fill:

```
$g_smtp_host = '';

...

$g_smtp_username = '';
$g_smtp_password = '';
$g_smtp_port = '';
$g_smtp_connection_mode = '';
```
Fill them with the following values (remember to substitute `YOUR_USERNAME` and `YOUR_PASSWORD` with valid values):
```
$g_smtp_host = 'smtp.gmail.com';

...

$g_smtp_username = 'YOUR_USERNAME@gmail.com';
$g_smtp_password = 'YOUR_PASSWORD';
$g_smtp_port = '587';
$g_smtp_connection_mode = 'tls';
```

Then, you will be able to send emails. Hope it helps.

**Comment by pwdavison** [comment]
@huiwu I think I am encountering this same issue. Below are steps to reproduce.

docker-compose.yml

```version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  testlink:
    image: 'bitnami/testlink:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    environment:
      - SMTP_ENABLE=true
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=my_user@gmail.com
      - SMTP_PASSWORD=my_password
      - SMTP_CONNECTION_MODE=tls
    volumes:
      - 'testlink_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
```

I then ran the command ```docker-compose up -d``` to build images/start container.

Once the containers are running, I get into the container using ```docker exec -it testlink_testlink_1 bash```


Then navigated to view custom_config.inc.php (/opt/bitnami/testlink)

```
<?php

$tlCfg->log_path = '/opt/bitnami/testlink/logs/';
$g_repositoryPath = '/opt/bitnami/testlink/upload_area/';
$tlCfg->config_check_warning_mode = 'SCREEN';
$g_smtp_host = '';
$g_tl_admin_email = 'user@example.com';
$g_from_email = 'user@example.com';
$g_return_path_email = 'user@example.com';
$g_smtp_username = '';
$g_smtp_password = '';
$g_smtp_port = '';
$g_smtp_connection_mode = '';

$tlCfg->default_language = 'en_US';

?>
```

Should the environment variables that I have specified in the docker-compose.yml for the smtp server settings get written into custom_config.inc.php?

**Comment by ae-dg** [comment]
I am seeing this as well. The environment is set in the docker-compose.yaml as when I exec in to the container I can see the variables with `env | grep SMTP` yet when I `cat /bitnami/testlink/custom_config.inc.php` the `$g_smtp_*` values are all empty.

Any advice would be appreciated.

**Comment by ae-dg** [comment]
To follow up...
I stopped everything and then did a `docker rmi` to remove the images and I noticed that it wasn't deleting the layers of the image; when I did a pull it told me 'Already exists' for each layer. `docker images -a` wasn't showing anything.
So I stopped everything, including docker itself, remove the contents of `/var/lib/docker` and tried again. This time the custom_config.inc.php was populated correctly. :-)

**Comment by pwdavison** [comment]
@juan131 I'm still facing the same issue even after trying what @ae-dg suggested. Can you explain how the smtp environment variables that I specify in the docker-compose.yml file get written to custome_config.inc.php?

**Comment by juan131** [comment]
Hi @ae-dg I'm glad you could initialise after removing the Image 😃 

@pwdavison yes of course! If you take a look the the **testlink-inputs.json** (https://github.com/bitnami/bitnami-docker-testlink/blob/master/1/rootfs/testlink-inputs.json), you'd find that it takes all the environment variables which are set related with TestLink and creates a .json file. That JSON file is then used as an input when TestLink Nami module is initialised in the **app-entrypoint.sh** (https://github.com/bitnami/bitnami-docker-testlink/blob/master/1/rootfs/app-entrypoint.sh)

**Comment by yuzhoualauda** [comment]
Hi there

I started the testlink and mariadb,and can create project and add test cases, thanks team.
But for the smtp config, even I modify the custom_config.inc.php manually, I still cannot reset the password of users.

The following is the custom_config.inc.php content inside the testlink container:
```
<vdl2g:/bitnami/testlink# cat custom_config.inc.php
<?php

$tlCfg->log_path = '/opt/bitnami/testlink/logs/';
$g_repositoryPath = '/opt/bitnami/testlink/upload_area/';
$tlCfg->config_check_warning_mode = 'SCREEN';
$g_smtp_host = 'smtp.163.com';
$g_tl_admin_email = 'yuzhou@alauda.io';
$g_from_email = 'yuzhou@alauda.io';
$g_return_path_email = 'yuzhou@alauda.io';
$g_smtp_username = 'mayzhou1314@163.com';
$g_smtp_password = 'my_password';
$g_smtp_port = '465';
$g_smtp_connection_mode = 'ssl';

$tlCfg->default_language = 'en_US';

?>
```
After clicking reset password, I get error in testlink container:
```
[08/Jan/2018:03:49:57 +0000] "GET /gui/themes/default/images//question.gif HTTP/1.1" 200 1044
 [08/Jan/2018:03:49:59 +0000] "POST /lib/usermanagement/usersEdit.php HTTP/1.1" 500 -
```
Can anyone please help? Thanks

**Comment by juan131** [comment]
Hi @yuzhoualauda 

Could you share what you obtain in the Apache Error Log? The one you'll find at `/opt/bitnami/apache/logs/error_log`.

**Comment by yuzhoualauda** [comment]
Hi @huiwu 

The following is the error for your reference:
`[Mon Jan 08 13:54:02.063482 2018] [:error] [pid 110] [client 10.0.5.1:42778] PHP Fatal error:  Uncaught phpmailerException: SMTP Error: data not accepted. in /opt/bitnami/testlink/third_party/phpmailer/class.phpmailer.php:1569\nStack trace:\n#0 /opt/bitnami/testlink/third_party/phpmailer/class.phpmailer.php(1335): PHPMailer->smtpSend('Date: Mon, 8 Ja...', '\\nYour new TestL...')\n#1 /opt/bitnami/testlink/third_party/phpmailer/class.phpmailer.php(1213): PHPMailer->postSend()\n#2 /opt/bitnami/testlink/lib/functions/email_api.php(162): PHPMailer->send()\n#3 /opt/bitnami/testlink/lib/functions/users.inc.php(214): email_send('yuzhou@alauda.i...', 'yuzhou@alauda.i...', 'Your new TestLi...', 'Your new TestLi...')\n#4 /opt/bitnami/testlink/lib/usermanagement/usersEdit.php(254): resetPassword(Object(database), 2, 'send_password_b...')\n#5 /opt/bitnami/testlink/lib/usermanagement/usersEdit.php(84): createNewPassword(Object(database), Object(stdClass), Object(tlUser), 'send_password_b...')\n#6 {main}\n  thrown in /opt/bitnami/testlink/third_party/phpmailer/class.phpmailer.php on line 1569, referer: http://testlink.testlink.nolimited.haproxy-54-223-242-27-alaudacn.myalauda.cn/lib/usermanagement/usersEdit.php?doAction=edit&loginJustToFixSort=yuzhou&user_id=2`

Hope it useful for you, thanks

**Comment by juan131** [comment]
Could you try by using the same mail account as "sender" and "username". I noticed you're using different accounts:

```
$g_tl_admin_email = 'yuzhou@alauda.io';
$g_from_email = 'yuzhou@alauda.io';
$g_return_path_email = 'yuzhou@alauda.io';
$g_smtp_username = 'mayzhou1314@163.com';
```

Answer based on https://stackoverflow.com/a/20887687/6694969

**Comment by yuzhoualauda** [comment]
Hi @juan131 

Issue got fixed, thanks a lot.

**Comment by juan131** [comment]
Glad to hear that! 😄

**Comment by Gulyna** [comment]
@juan131 I encountered a similar issue with this. But I deployed Test Link on Ali Cloud. After I set the environment in docker-compose and log in Test Link, there is an error message said "please check the parameter smtp host". It seems the setting in docker compose didn't take effect, it disappeared after I modified custom_config.inc.php manually to add smtp host.  Could you help on this? BTW, there is another error message "the installation directory should be removed", but I can't find the directory. Thanks!

----------------------my docker compose file-------------------------
mariadb:
  image: 'bitnami/mariadb:latest'
  environment:
    - ALLOW_EMPTY_PASSWORD=yes
  restart: always
  volumes:
    - 'testlink-db:/bitnami:rw'
testlink:
  image: 'bitnami/testlink:latest'
  ports:
    - '8189:80'
    - '443:443'
  restart: always
  environment:
   SMTP_ENABLED: "true"
   SMTP_DOMAIN: "exmail.qq.com"
   SMTP_HOST: "smtp.exmail.qq.com"
   SMTP_PORT: 465
   SMTP_STARTTLS: "true"
  labels:
    aliyun.lb.port_80: 'http://lb-2zeezt23f3kw3dh2mfq1y:80'
    aliyun.lb.port_443: 'tcp://lb-2zeezt23f3kw3dh2mfq1y:443'
    aliyun.scale: '1'
    kompose.service.type: nodeport
  volumes:
    - 'testlink:/bitnami:rw'
  depends_on:
    - mariadb
  links:
    - mariadb:mariadb
-----------------------my docker compose file----------------------

**Comment by javsalgar** [comment]
Hi,

I don't have much knowledge about how Ali Cloud works. My advice would be to do a docker-compose down (if possible, with the `-v` flag for removing volumes in case you do not have any important data in the instance) and then execute `docker-compose up`.

**Comment by juan131** [comment]
Hi @Gulyna 

You're environment it's so weird. You're using **SMTP_DOMAIN** and **SMTP_STARTTLS** which are not valid env variables. You're using **SMTP_ENABLED** instead of **SMTP_ENABLE** too. The environment should look like:

```
    - SMTP_ENABLE=true
    - SMTP_HOST=exmail.qq.com
    - SMTP_PORT=465
    - SMTP_USER=your_mail
    - SMTP_PASSWORD=your_password
    - SMTP_CONNECTION_MODE=tls
```

>  Do I need to run docker-compose up -d after I change compose file? or Redeploy button in Ali Cloud Application List page did the same thing? Thanks.

I have never used Ali Cloud so I don't know what actions are triggered when you click the "redeploy" button. You'd better contact Ali Cloud support for that.

**Comment by Gulyna** [comment]
@javsalgar Thank you very much, I'll try it.
@juan131 That's because the smtp setting didn't work after I follow above instruction and I tried various methods I found on internet :(  thanks a lot for your suggestion.

**Comment by juan131** [comment]
Hi @Gulyna 

Please let us know if @javsalgar suggestion worked when you have a chance to try it.

**Comment by ghisvail** [comment]
The [SMTP configuration](https://github.com/bitnami/bitnami-docker-testlink#smtp-configuration) does not work for me. I first deployed `testlink` without SMTP configuration, and I am now trying to add it to enable password resets.

I ran `docker-compose down`, followed by editing the `docker-compose.yml` file with the appropriate SMTP settings and launch it back with `docker-compose up -d`. No success. Password reset complains the SMTP host is not configured properly.

**Comment by andresbono** [comment]
Hi @ghisvail, the SMTP environment variables take effect in the initialization of the application only. So you will need to choose one of the following options:
- Remove the persistent volume associated to the application. You will loose all the application data by doing it. Then, you can reinitialize the application and the SMTP environment variables will be applied.
```
docker-compose down --volumes
docker-compose up
```

- Change the configuration file manually as explained here: https://github.com/bitnami/bitnami-docker-testlink/issues/49#issuecomment-343933443.

Let us know if this works for you.

-Andrés B.
