### ISSUE TITLE
Containers are not upgrading from 1.9.15-r3 to latest

### ISSUE THREAD

**Issue by kylemanel** [bitnami/bitnami-docker-testlink#51]
_**Containers are not upgrading**_

**To upgrade;**
1. [First Step: stop containers]
```
 docker stop testlink_application_1
 docker stop testlink_mariadb_1
```
2. [Remove containers]
```
 docker rm testlink_application_1
 docker rm testlink_mariadb_1
```
3. [Second Step: update containers]
```
 docker pull bitnami/testlink:latest
 docker pull bitnami/mariadb:latest
```
3. [Review docker-compose.yml to verify versions are set to 'latest']
```
''
    image: 'bitnami/maraidb:latest'
''
    image: 'bitnami/testlink:latest'
''
```
5. [Run the docker-compose process]
```
 cd /dir/with/dockercompose.yml/
 docker-compose up
```

_**Describe the results you received:**_
Once this configuration occurs, when using my login page I receive the following:
`You need to proceed with Manual upgrade of your DB scheme to DB 1.9.15 - Read README file!`
**NOTE version 1.9.15 does not exist for bitnami/mariadb**

On review of the README.md either [here (for testlink)](https://github.com/bitnami/bitnami-docker-testlink/blob/master/README.md) or [here (for mariadb)](https://github.com/bitnami/bitnami-docker-mariadb/blob/master/README.md), neither suggests how to resolve this issue; They provide information on how to deploy, configure and upgrade, which are the same steps I followed.

_**Describe the results you expected:**_
I expect the application to be running (presumably with the latest version of mariadb as well as testlink)

_**Additional information you deem important:**_
_When I run my older db container with a new testlink server the same error occurs as above:_
`You need to proceed with Manual upgrade of your DB scheme to DB 1.9.15 - Read README file!`

_When I run a new db container with an old version of testlink the service runs successfully, and on CLI during load informs me:_
`*** New version available: run docker pull bitnami/testlink:1.9.16-r7 to update. ***`

**Testlink Version information:**
1.9.15-r3 -> latest (r7)

**- Output of `docker version`:**
```
inbay@docker1-int:~/testlink$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**- Output of `docker info`:**
```
inbay@docker1-int:~/testlink$ docker info
Containers: 17
 Running: 12
 Paused: 0
 Stopped: 5
Images: 119
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 811
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: docker1-int
ID: JNRV:TEOV:OXLL:AZ22:4JUB:6GY6:HFGF:KJIN:YQNX:VZKD:6H74:BVZY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**- Output of `docker-compose version`:**
```
inbay@docker1-int:~/testlink$ docker-compose version
docker-compose version 1.11.1, build 7c5d5e4
docker-py version: 2.0.2
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Comment by sameersbn** [comment]
Hi and sorry of the delay in our response.

**Please note that we have not throughly tested the below mentioned procedure. 
You are hereby advised to backup the database and application data before executing the commands listed below.**

Unfortunately the testlink application does not automatically perform schema updates so we need to do them manually.

First, login to the running container shell using `docker exec -it <container-id> bash` and execute the following commands to upgrade the database schema:

```bash
# fetch the database connection parameters
DB_HOST=$(sed -n -e "s/\([ ]*\)\(define('DB_HOST', '\)\([^ ']*\)\(.*\)$/\3/p" /bitnami/testlink/config_db.inc.php)
DB_USER=$(sed -n -e "s/\([ ]*\)\(define('DB_USER', '\)\([^ ']*\)\(.*\)$/\3/p" /bitnami/testlink/config_db.inc.php)
DB_PASS=$(sed -n -e "s/\([ ]*\)\(define('DB_PASS', '\)\([^ ']*\)\(.*\)$/\3/p" /bitnami/testlink/config_db.inc.php)
DB_NAME=$(sed -n -e "s/\([ ]*\)\(define('DB_NAME', '\)\([^ ']*\)\(.*\)$/\3/p" /bitnami/testlink/config_db.inc.php)
# perform upgrade steps listed in /opt/bitnami/testlink/README
sed 's/\/\*prefix\*\///g' /opt/bitnami/testlink/install/sql/alter_tables/1.9.16/mysql/DB.1.9.16/step1/db_schema_update.sql | mysql -h$DB_HOST -u$DB_USER -p$DB_PASS $DB_NAME
sed 's/\/\*prefix\*\///g' /opt/bitnami/testlink/install/sql/alter_tables/1.9.16/mysql/DB.1.9.16/stepZ/z_final_step.sql | mysql -h$DB_HOST -u$DB_USER -p$DB_PASS $DB_NAME
```

Typically this is all that should be needed, but we realized that there is an issue in the bitnami/testlink image where the version in the configuration file is not automatically updated. To work around this issue, execute the following command in the `docker exec` shell of the container.

```bash
# manually update the version listed in the config file
sed -i "s/define('TL_VERSION_NUMBER', '1.9.15')/define('TL_VERSION_NUMBER', '1.9.16')/" /bitnami/testlink/cfg/const.inc.php
```

You should now be able to access the updated TestLink version.

**Comment by sameersbn** [comment]
@kylemanel we're you able to perform the upgrade using the instructions from my earlier response?

**Comment by kylemanel** [comment]
Hello Sameer,
I have been at conference over the last half of last week.  I will be
reviewing this tomorrow.
Many thanks for your patience,
Kyle

**Comment by arapulido** [comment]
@kylemanel Any updates from your side?

**Comment by kylemanel** [comment]
Hi Sameer,

My apologies, this got away from me as this is my private e-mail address.
I've attached my business address now as well, so I will be looking into it
again on Monday.

**Comment by arapulido** [comment]
@kylemanel Any news on this? Shall we close the issue and if you are able to test it and it doesn't work for you re-open it?

**Comment by kylemanel** [comment]
**Hello Ara,

Sorry for the delay on my part.

My sed is a little rough, but I believe the lines provided above;**

# fetch the database connection parameters
DB_HOST=$(sed -n -e "s/\([ ]*\)\(define('DB_HOST', '\)\([^ ']*\)\(.*\)$/\3/p" /bitnami/testlink/config_db.inc.php)
DB_USER=$(sed -n -e "s/\([ ]*\)\(define('DB_USER', '\)\([^ ']*\)\(.*\)$/\3/p" /bitnami/testlink/config_db.inc.php)
DB_PASS=$(sed -n -e "s/\([ ]*\)\(define('DB_PASS', '\)\([^ ']*\)\(.*\)$/\3/p" /bitnami/testlink/config_db.inc.php)
DB_NAME=$(sed -n -e "s/\([ ]*\)\(define('DB_NAME', '\)\([^ ']*\)\(.*\)$/\3/p" /bitnami/testlink/config_db.inc.php)
# perform upgrade steps listed in /opt/bitnami/testlink/README
sed 's/\/\*prefix\*\///g' /opt/bitnami/testlink/install/sql/alter_tables/1.9.16/mysql/DB.1.9.16/step1/db_schema_update.sql | mysql -h$DB_HOST -u$DB_USER -p$DB_PASS $DB_NAME
sed 's/\/\*prefix\*\///g' /opt/bitnami/testlink/install/sql/alter_tables/1.9.16/mysql/DB.1.9.16/stepZ/z_final_step.sql | mysql -h$DB_HOST -u$DB_USER -p$DB_PASS $DB_NAME
# manually update the version listed in the config file
sed -i "s/define('TL_VERSION_NUMBER', '1.9.15')/define('TL_VERSION_NUMBER', '1.9.16')/" /bitnami/testlink/cfg/const.inc.php


**Will modify the following files;**
/bitnami/testlink/config_db.inc.php
/opt/bitnami/testlink/install/sql/alter_tables/1.9.16/mysql/DB.1.9.16/step1/db_schema_update.sql
/opt/bitnami/testlink/install/sql/alter_tables/1.9.16/mysql/DB.1.9.16/stepZ/z_final_step.sql
/bitnami/testlink/cfg/const.inc.php

**However, the following files do not exist in the container:**
/opt/bitnami/testlink/install/sql/alter_tables/1.9.16/mysql/DB.1.9.16/step1/db_schema_update.sql
/opt/bitnami/testlink/install/sql/alter_tables/1.9.16/mysql/DB.1.9.16/stepZ/z_final_step.sql

**Comment by hechi** [comment]
Before you try the sql command, make a backup of your database!
ex. MariaDB
`$ rsync -a /path/to/mariadb-persistence /path/to/mariadb-persistence.bkp.$(date +%Y%m%d-%H.%M.%S)
`

@sameersbn thx for the commands :) the worked almost. I had to change both sql scripts because the have some problem with the primarykey which already exists and also with the _insert into_ of a role (8,30).

> sed 's/\/\*prefix\*\///g' /opt/bitnami/testlink/install/sql/alter_tables/1.9.17/mysql/DB.1.9.17/step1/db_schema_update.sql | mysql -hmariadb -u$DB_USER -p$DB_PASS $DB_NAME
ERROR 1060 (42S21) at line 2: Duplicate column name 'tcstep_id'

> sed 's/\/\*prefix\*\///g' /opt/bitnami/testlink/install/sql/alter_tables/1.9.17/mysql/DB.1.9.17/step1/db_schema_update.sql | mysql -h$DB_HOST -u$DB_USER -p$DB_PASS $DB_NAME
ERROR 1062 (23000) at line 67: Duplicate entry '8-30' for key 'PRIMARY' 

I also had problems with the DB_NAME because if they are not defined testlink uses default one but the name is empty.

I updated from version 1.9.16 to 1.9.17. I mention it only if someone has similar problems.

**Comment by juan131** [comment]
Hi @hechi 

> Before you try the sql command, make a backup of your database!

+100!! It's always a good practise. Docs about backups on this [link](https://docs.bitnami.com/general/components/mysql/#how-to-create-a-database-backup)

> I updated from version 1.9.16 to 1.9.17. I mention it only if someone has similar problems.

Thanks for sharing your solution! I'm sure it'll help a lot users on similar situations.

**Comment by alandolsi** [comment]
I have the same problem update testlink 1.9.16 to 1.9.17
ERROR 1062 (23000) at line 67: Duplicate entry '8-30' for key 'PRIMARY'

is there a solution?

**Comment by juan131** [comment]
Hi @alandolsi 

Did you check @hechi last answer? You need to apply the corresponding substitutions to the SQL scripts and modify them to avoid creating the primary key since it already exists.
