### ISSUE TITLE
can I specify database use ENV variable?

### ISSUE THREAD

**Issue by sfwn** [bitnami/bitnami-docker-testlink#53]
I know I can specify `MARIADB_USER / MARIADB_PASSWORD / MARIADB_HOST / MARIADB_PORT_NUMBER`.

Can I also specify which db to use? Because I have bought a `mysql service` on SaaS, unfortunately I cannot change the db-name again.

Thank you.

**Comment by andresbono** [comment]
Hi @sfwn, I'm afraid that this is not currently supported for our TestLink container.

However, as it seems a beneficial feature, we will investigate the possibility to implement it in the future.

Thanks for your feedback!

**Comment by Rohlik** [comment]
Would be nice, when I can specify **DB_TYPE**. For example, we want use testlink with postgres.

**Comment by juan131** [comment]
Hi @Rohlik I think it's interesting to include this possibility on every Bitnami Docker Image with application that support more than one database (PostgreSQL, MariaDB, MySQL, etc.)

What do you think @tompizmor @jotadrilo  ? 

> Note: I created an internal task requesting this feature.

**Comment by jseadragon** [comment]
The ability to run this image with postgres would be quite useful.

**Comment by CamilleBarnier** [comment]
to change Host for db use :
sed -i 's/mariadb/yourHost/g' bitnami/testlink/config_db.inc.php

**Comment by andresbono** [comment]
Thanks for providing this workaround, @CamilleBarnier.

**Comment by andresbono** [comment]
Hi all, we have released a new version of the container that now adds a new environment variable for the database name `TESTLINK_DATABASE_NAME`, see [Environment variables](https://github.com/bitnami/bitnami-docker-testlink#environment-variables) section for more information.

**Comment by prcongithub** [comment]
Does this support postgresql now?

**Comment by juan131** [comment]
Hi @prcongithub 

I'm afraid it does not. As you can see, we only include a `mysql client` in the image:

- https://github.com/bitnami/bitnami-docker-testlink/blob/master/1/debian-10/Dockerfile#L14

We provided support for using an existing Testlink database in a MySQL/MariaDB server as it's explained in the link below:

- https://github.com/bitnami/bitnami-docker-testlink#use-an-existing-database

**Comment by prcongithub** [comment]
Thanks for confirming.
