### ISSUE TITLE
Run TestLink on sub-directory http://site/testlink

### ISSUE THREAD

**Issue by nanorobocop** [bitnami/bitnami-docker-testlink#54]
Hello, 

Could you please describe how to run TestLink on sub-directory?
I mean there's site http://site/ and I want to have TestLink available on http://site/testlink.

I tried ProxyPass and ProxyPassReverse in Apache, but all links are still don't know about /testlink subdir.
There should be something like base url or root path, but cannot find in settings.

Thanks in advance!

**Comment by tompizmor** [comment]
Hello @nanorobocop,

I think the simple solution would be to stop using the virtual host file and use an use an alias for Testlink instead.

Would you mind trying the following steps?

1. Log into the testlink container
2. Open `/opt/bitnami/apache/conf/httpd.conf` file and comment the following line:

```
IncludeOptional /opt/bitnami/apache/conf/vhosts/*.conf
```

3. Add the following line to `/opt/bitnami/apache/conf/httpd.conf`

```
Include /opt/bitnami/apache/conf/testlink.conf
```

4. Create `/opt/bitnami/apache/conf/testlink.conf` file with the following content:

```
Alias /testlink/ "/opt/bitnami/testlink/"
Alias /testlink "/opt/bitnami/testlink"

  <Directory "/opt/bitnami/testlink">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride None
    Require all granted
    DirectoryIndex index.html index.php


  </Directory>
  Include /opt/bitnami/apache/conf/vhosts/htaccess/testlink-htaccess.conf
```

5. Restart apache

```
$ nami restart apache
```

I hope it helps!

**Comment by nanorobocop** [comment]
Thank you for this information!

**Comment by juan131** [comment]
Hi @nanorobocop 
Did the workaround @tompizmor suggested you work? I proceed to close this issue but please feel free to open it if you require further assistance to configure Apache+Testlink

**Comment by nanorobocop** [comment]
Yes, it works! Thanks! :)
