### ISSUE TITLE
smtp not working, please help to confirm

### ISSUE THREAD

**Issue by yuzhoualauda** [bitnami/bitnami-docker-testlink#57]
**Description**

**Steps to reproduce the issue:**

1. I use docker-compose up to start the testlink and mariadb, they already started and running
2. I added the envs to the testlink container, below is the env:
    [root@172 centos]# docker exec -it 8b82174b7b3c env | grep SMTP
SMTP_CONNECTION_MODE=ssl
SMTP_HOST=smtp.163.com
SMTP_ENABLE=true
SMTP_USER=mayzhou1314@163.com
SMTP_PORT=465
SMTP_PASSWORD=Zhouyu0401
TESTLINK_EMAIL=yuzhou@alauda.io
TESTLINK_USERNAME=admin
TESTLINK_PASSWORD=admin_testlink

3. I can open the testlink home page and login successfully
4. Then I create an user and try to reset the password
5. but when I click reset password, page shows the blank page which I am attached.
![testlink_reset_password](https://user-images.githubusercontent.com/23095094/34607794-2fe8b812-f250-11e7-8d2c-9667837bfbaa.jpeg)

**Describe the results you received:**

I got the error below:
[05/Jan/2018:11:21:16 +0000] "GET /lostPassword.php?viewer=new HTTP/1.1" 200 763
 [05/Jan/2018:11:21:20 +0000] "POST /lostPassword.php?viewer=new HTTP/1.1" 500 -

**Describe the results you expected:**
I should receive the email.

and can not receive any email from testlink.  

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
[root@172 centos]# docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:19 2017
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:19 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

- Output of `docker info`:

```
[root@172 centos]# docker info
Containers: 65
 Running: 65
 Paused: 0
 Stopped: 0
Images: 35
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-202:1-494929417-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 22.15 GB
 Data Space Total: 107.4 GB
 Data Space Available: 85.23 GB
 Metadata Space Used: 30.15 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.117 GB
 Thin Pool Minimum Free Space: 0 B
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: fluentd
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 29.04 GiB
Name: 172.31.26.85
ID: K4CV:F7JR:HNSE:5ST2:K2VY:APDT:YLIZ:WL6C:M5GN:NXKK:KGQM:J7EX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: true
Insecure Registries:
 172.31.20.1:28086
 172.31.29.191:5000
 172.31.3.208:5000
 172.31.32.238:5000
 172.31.20.1:28086
 172.31.20.1
 172.31.30.69:5000
 127.0.0.0/8
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
AWS's R3.2Xlarge machine

**Comment by juan131** [comment]
As I mentioned at https://github.com/bitnami/bitnami-docker-testlink/issues/49

Could you please share the content of the Apache Error Log? Let's try to debug the reason why you're facing the 500 error.

**Comment by yuzhoualauda** [comment]
Hi @juan131 

By using the same mail account as "sender" and "username" like below, issue fixed.
```
$g_tl_admin_email = 'test@example.io';
$g_from_email = 'test@example.io';
$g_return_path_email = 'test@example.io';
$g_smtp_username = 'test@example.io';
```

Answer based on https://stackoverflow.com/a/20887687/6694969.

Thanks a lot for your help. 👍

**Comment by andresbono** [comment]
Great to hear, @yuzhoualauda!! 🎉
