### ISSUE TITLE
Unable to run testlink behind nginx proxy

### ISSUE THREAD

**Issue by tboloo** [bitnami/bitnami-docker-testlink#60]
**Description**

I am trying to run testling behind the nginx proxy. 
In order to do so, I have slightly modified provided docker-compose file to expose testlink on ports different then 80 and 443, and configured nginx as a proxy, with following configuration:

```
upstream testlink {
    server 77.55.215.210:7080;
}

server {
    server_name testlink.my-server-address;;
    listen 80;
    listen [::]:80;
    return 301 https://testlink.my-server-addressl$request_uri;
}

server {
	server_name testlink.my-server-address;
	# SSL configuration
	#
	listen 443 ssl;
	listen [::]:443 ssl;

	ssl_certificate /etc/letsencrypt/live/my-server-address/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/my-server-address/privkey.pem;

	location / {
      	proxy_http_version 1.1;
      	proxy_pass http://testlink;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
  	}
}
```

which doesn't quite work - I can login to TestLink, but it seems that not all scripts and styles gets loaded:
![image](https://user-images.githubusercontent.com/499405/35595138-e9c98fe4-0615-11e8-8361-f9d5c590ee96.png)

**Steps to reproduce the issue:**

1. run docker-compose up
2. setup nginx virtual host as above

**Additional information you deem important (e.g. issue happens only occasionally):**

testling and mariadb tag - latest

**Version**

- Output of `docker version`:

```
 17.12.0-ce
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.0, build ac53b73
```

**Additional environment details**
Running on VPS, 
Distributor ID: Debian
Description:    Debian GNU/Linux 9.3 (stretch)
Release:        9.3
Codename:       stretch

**Comment by javsalgar** [comment]
Could you show what the Chrome Web Inspector console shows? This would help us to better understand what is happening.

**Comment by tboloo** [comment]
It seems that requests for css are requested through http, not https:
`navBar.php:18 Mixed Content: The page at 'https://testlink.my-server-address/' was loaded over HTTPS, but requested an insecure stylesheet 'http://testlink.my-server-address/gui/themes/default/css/testlink.css'. This request has been blocked; the content must be served over HTTPS.`

**Comment by tboloo** [comment]
Ok, I found the solution: one has to add
`        proxy_set_header X-Forwarded-Proto https;`
to the nginx configuration in location / section.

```
	location / {
      	    proxy_http_version 1.1;
      	    proxy_pass http://testlink;
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
  	}
```
