### ISSUE TITLE
Accessing to xmlrpc API

### ISSUE THREAD

**Issue by MarcoCaballero** [bitnami/bitnami-docker-testlink#62]
Why I always get 404 Not Found from localhost:80/tetstlink..../v1/xmlrpc.php and localhost:80/opt/bitnami/tetstlink..../v1/xmlrpc.php. 
How could I set Apache htaccess or any .conf to allow xmlrpc calls from any Testlink XMLRPC API.

Thanks in advance.

**Comment by juan131** [comment]
Hi @MarcoCaballero 

Could you please share the content of the Apache access log? You can find it under `/opt/bitnami/apache/logs/access_log`? I want to debug the reason why you're obtaining the 404 response.

**Comment by MarcoCaballero** [comment]
Hi @juan131, thanks for the answer, it was my doing. I was calling `localhost/testlink/.../xmlrpc.php` but the proper path is `localhost/..../xmlrpc.php`.

**Comment by juan131** [comment]
Hi @MarcoCaballero 

Oh great!! I am glad that you were able to fix the issue. I proceed to close it, please feel free to open it you need further help
