### ISSUE TITLE
Error executing 'postInstallation': EACCES: permission denied, open '/bitnami/apache/conf/bitnami/bitnami.conf'

### ISSUE THREAD

**Issue by sugirthan4694** [bitnami/bitnami-docker-testlink#67]
I'm getting error as when hitting the testlink server

My docker-compose.yml file looks like 

version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
    volumes:
      - 'mariadb_data:/bitnami'
  testlink:
    image: 'bitnami/testlink:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USER=xxxxx@gmail.com
      - SMTP_PASSWORD=yyyyyyyy
      - SMTP_CONNECTION_MODE=ssl
    volumes:
      - 'testlink_data:/bitnami'
      - '/root/certs:/bitnami/apache/conf/bitnami/certs'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local

**Version**

[root@testlink-labs ~]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-63.git94f4240.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      94f4240/1.13.1
 Built:           Fri May 18 15:44:33 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-63.git94f4240.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      94f4240/1.13.1
 Built:           Fri May 18 15:44:33 2018
 OS/Arch:         linux/amd64
 Experimental:    false
[root@testlink-labs ~]# docker info
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 2
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: e9c345b3f906d5dc5e8100b05ce37073a811c74a (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: 5b117de7f824f3d3825737cf09581645abbe35d4 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-862.2.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 2
Total Memory: 7.147 GiB
Name: testlink-labs
ID: JY2L:BWU5:6ITB:P2NW:V6GF:JHAM:MXYF:2E4R:BHF7:VWTD:LJZH:2XMB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
[root@testlink-labs ~]# docker-compose version
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
[root@testlink-labs ~]# 

the error logs are 

mariadb logs 

Welcome to the Bitnami mariadb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing mariadb
mariadb INFO 
mariadb INFO  ########################################################################
mariadb INFO   Installation parameters for mariadb:
mariadb INFO     Persisted data and properties have been restored.
mariadb INFO     Any input specified will not take effect.
mariadb INFO   This installation requires no credentials.
mariadb INFO  ########################################################################
mariadb INFO 
nami    INFO  mariadb successfully initialized
INFO  ==> Starting mariadb... 
INFO  ==> Starting mysqld_safe...
180601 11:38:34 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
180601 11:38:34 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data

Welcome to the Bitnami mariadb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
INFO  ==> Starting mariadb... 
INFO  ==> Starting mysqld_safe...
180601 11:42:31 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
180601 11:42:31 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data

testlink logs 

Welcome to the Bitnami testlink container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-testlink
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-testlink/issues

nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
Error executing 'postInstallation': EACCES: permission denied, open '/bitnami/apache/conf/bitnami/bitnami.conf'

**Comment by javsalgar** [comment]
Hi,

I think the issue is here: `- '/root/certs:/bitnami/apache/conf/bitnami/certs'`. The subfolders that are being created (conf and bitnami) do not have the proper permissions. Could you mount something like this instead?

`- '/root/apache:/bitnami/apache'`

And then, inside `/root/apache`, create the subfolder `conf/bitnami/certs` with the proper write permissions.
