### ISSUE TITLE
testlink can't start with error message "Error executing 'postInstallation': "port" option should be >= 0 and < 65536: tcp://xxx.xx.xxx.xx:3306"

### ISSUE THREAD

**Issue by Gulyna** [bitnami/bitnami-docker-testlink#68]
**Description**
testlink can't start with error message "Error executing 'postInstallation': "port" option should be >= 0 and < 65536: tcp://172.20.197.5:3306". and status in containers are always "restarting", and the health check is "unknown" .

**Steps to reproduce the issue:**

1. install testlink with bitnami-docker-testlink 
2. move the application from one node to another
3. access testlink (it works before move the application)

**Describe the results you received:**

Error executing 'postInstallation': "port" option should be >= 0 and < 65536: tcp://172.20.197.5:3306

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

Docker version 17.06.2-ce, build 2e0fd6f

- Output of `docker info`:

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by tompizmor** [comment]
Hi @Gulyna,

Could you please let me know the Testlink version that you are using?
Also, could you share more information about what means move the application from one node to another? Are you using kubernetes? If so, how are you moving the application?

**Comment by Gulyna** [comment]
Hi @tompizmor 

Do you mean docker image version for testlink? If yes, it is: bitnami/testlink:1.9.15-r0. 

I am using Swarm.  Sorry, it should be I rescheduled the testlink and mariadb service from one node to another by clicking clicking "reschedule" button in Service List. I checked both of "Ignore Local Volumes" and "Force Reschedule" in pop up page :(
![reschedule](https://user-images.githubusercontent.com/36398117/41030325-a4948074-69b0-11e8-90fd-c5f27b595e06.jpeg)

**Comment by tompizmor** [comment]
Have you tried without checked "Ignore Local Volumes" ? I guess that when you move Testlink from one node to another you would want to preserve the current status of the application.

Could you also try with a newer verison of Testink? Old versions like the one you are using had an issue regarding a environment variable collision, at least in Kubernetes, so maybe is happening the same with docker swarm. `1.9.17-r34` is the latest version, can you try that?

**Comment by Gulyna** [comment]
Hi @tompizmor 

There are following error messages after i use the latest version:

testlink_testlink_1 | 2018-06-07T10:28:30.063043186Z [0m
testlink_testlink_1 | 2018-06-07T10:28:30.072252082Z [0m[1mWelcome to the Bitnami testlink container[0m
testlink_testlink_1 | 2018-06-07T10:28:30.072670028Z [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-testlink[0m
testlink_testlink_1 | 2018-06-07T10:28:30.072688316Z [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-testlink/issues[0m
testlink_testlink_1 | 2018-06-07T10:28:30.072691436Z [0m
testlink_testlink_1 | 2018-06-07T10:28:32.988785409Z nami    INFO  Initializing apache
testlink_testlink_1 | 2018-06-07T10:28:33.026668960Z apache  INFO  ==> Reconfiguring PID file location...
testlink_testlink_1 | 2018-06-07T10:28:33.379860177Z nami    INFO  apache successfully initialized
testlink_testlink_1 | 2018-06-07T10:28:36.383832775Z nami    INFO  Initializing php
testlink_testlink_1 | 2018-06-07T10:28:36.473327897Z nami    INFO  php successfully initialized
testlink_testlink_1 | 2018-06-07T10:28:38.885559234Z nami    INFO  Initializing mysql-client
testlink_testlink_1 | 2018-06-07T10:28:38.914465278Z nami    INFO  mysql-client successfully initialized
testlink_testlink_1 | 2018-06-07T10:28:41.873737083Z nami    INFO  Initializing testlink
testlink_testlink_1 | 2018-06-07T10:29:14.151072938Z Error executing 'postInstallation': Unable to start com.bitnami.apache: httpd: Syntax error on line 156 of /opt/bitnami/apache/conf/httpd.conf: Cannot load modules/libphp5.so into server: /opt/bitnami/apache/modules/libphp5.so: cannot open shared object file: No such file or directory
testlink_testlink_1 | 2018-06-07T10:29:14.151103501Z : httpd: Syntax error on line 156 of /opt/bitnami/apache/conf/httpd.conf: Cannot load modules/libphp5.so into server: /opt/bitnami/apache/modules/libphp5.so: cannot open shared object file: No such file or directory
testlink_testlink_1 | 2018-06-07T10:29:14.151108138Z 
testlink_testlink_1 | 2018-06-07T10:30:03.452145949Z [0m
testlink_testlink_1 | 2018-06-07T10:30:03.452176277Z [0m[1mWelcome to the Bitnami testlink container[0m
testlink_testlink_1 | 2018-06-07T10:30:03.452179757Z [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-testlink[0m
testlink_testlink_1 | 2018-06-07T10:30:03.452187312Z [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-testlink/issues[0m
testlink_testlink_1 | 2018-06-07T10:30:03.452190442Z [0m
testlink_testlink_1 | 2018-06-07T10:30:10.429531017Z nami    INFO  Initializing testlink
testlink_testlink_1 | 2018-06-07T10:30:42.693227155Z Error executing 'postInstallation': Unable to start com.bitnami.apache: httpd: Syntax error on line 156 of /opt/bitnami/apache/conf/httpd.conf: Cannot load modules/libphp5.so into server: /opt/bitnami/apache/modules/libphp5.so: cannot open shared object file: No such file or directory
testlink_testlink_1 | 2018-06-07T10:30:42.693256837Z : httpd: Syntax error on line 156 of /opt/bitnami/apache/conf/httpd.conf: Cannot load modules/libphp5.so into server: /opt/bitnami/apache/modules/libphp5.so: cannot open shared object file: No such file or directory
testlink_testlink_1 | 2018-06-07T10:30:42.693261578Z

**Comment by tompizmor** [comment]
I think the issue is that you have the apache configuration persisted.

In your old version, Testlink was using php5 but the new version uses php7. As the Apache configuration is persisted from the old version is trying to load `libphp5.so` (which is missing in the new image) instead of `libphp7.so`.

You should clean your volumes to start from scratch or in case there are data that you want to save, you would need to edit the file `/opt/bitnami/apache/conf/httpd.conf` to load the proper version of the libphp module.

**Comment by Gulyna** [comment]
Hi @tompizmor I updated the testlink version to the latest one, but there are some different error messages, please refer to the attached log.
![error](https://user-images.githubusercontent.com/36398117/41213015-ef3655c2-6d74-11e8-82a4-d801bb05a36f.png)
[error log.pdf](https://github.com/bitnami/bitnami-docker-testlink/files/2088714/error.log.pdf)

**Comment by tompizmor** [comment]
Are you seeing this error on a fresh installation or after trying to re-schedule the application into another node?

Also, did you remove all the volumes before trying with the latest version of Testlink?

**Comment by Gulyna** [comment]
Hi @tompizmor 

I found this error after i update the testlink from 1.9.15-r0 to 1.9.17-r34. I didn't remove the volumes but updated /opt/bitnami/apache/conf/httpd.conf. 

I found a similar issue and trying to update the schema manually, but for now I can't install "rsync" on the container.

https://github.com/bitnami/bitnami-docker-testlink/issues/51

**Comment by Gulyna** [comment]
Hi @tompizmor 

I fixed this issue by updating testlink version from 1.9.15 to 1.9.16 and manually update the version in config file.

# manually update the version listed in the config file
sed -i "s/define('TL_VERSION_NUMBER', '1.9.15')/define('TL_VERSION_NUMBER', '1.9.16')/" /bitnami/testlink/cfg/const.inc.php

**Comment by tompizmor** [comment]
We are glad that you were able to fix the issue.

**Comment by Gulyna** [comment]
Hi @tompizmor Thanks, but i think it'll be more convenient if testlink could update the schema automatically rather than updated by user manually   :)

**Comment by tompizmor** [comment]
@Gulyna I agree! Could you please tell me which procedure did you follow to manually update the database schema? We can work on adding that functionality for future versions of testlink.

**Comment by Gulyna** [comment]
@tompizmor please refer to sameersbn's comment in https://github.com/bitnami/bitnami-docker-testlink/issues/51,  but the issue is still open and i don't know if it works. 

For me, when i tried following commands, there is an error message "ERROR 1062 (23000) at line 67: Duplicate entry '8-30' for key 'PRIMARY'", so I gave up 1.9.17 and downgrade testlink version from 1.9.17 to 1.9.16.

> sed 's//*prefix*///g' /opt/bitnami/testlink/install/sql/alter_tables/1.9.17/mysql/DB.1.9.17/step1/db_schema_update.sql | mysql -h$DB_HOST -u$DB_USER -p$DB_PASS $DB_NAME

**Comment by tompizmor** [comment]
@Gulyna I can reproduce the issue of upgrading the container to the 1.9.17 version. I just wanted to let you know that we will try to fix it for future releases.
