### ISSUE TITLE
Issue Tracker connection settings applay only on conteiner recreate.

### ISSUE THREAD

**Issue by ASLanin** [bitnami/bitnami-docker-testlink#69]
echo $BITNAMI_IMAGE_VERSION
1.9.16-r8

**Description**
Issue Tracker (youtrack) connection settings (page "System"->"Issue Tracker Management") applays only at container create/recreate
If Tracking system is unaveliable at the testlink container creation moment, I have error message "Attention Please: 
Something is preventing connection to Bug Tracking System,
and is going to create performance issues.
Please contact your TestLink Administrator" on "Test Results on Build" page.

**Steps to reproduce the issue:**
0. start issue tracker (youtrack)
1. create testlink container
2. configure Issue Tracker connection settings and check it OK
3. go to page  "Test Results on Build" and see error message
4. recreate container
5. go to page  "Test Results on Build" and all go fine

OR

0. stop issue tracker
1. recreate testlink container (config data saved at volume)
2. go to page  "Test Results on Build" and see error message
3. start issue tracker
4. go to page  "Test Results on Build" and see error message
No way to connect to the youtrack until nexux container recreation.

**Describe the results you received:**

Error message:"Attention Please: 
Something is preventing connection to Bug Tracking System,
and is going to create performance issues.
Please contact your TestLink Administrator"

**Describe the results you expected:**
Link issue icons on TestResult page and no error message

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

- Output of `docker info`:

```
Containers: 13
 Running: 10
 Paused: 0
 Stopped: 3
Images: 24
Server Version: 18.03.1-ce
Storage Driver: devicemapper
 Pool Name: docker_data-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data Space Used: 10.18GB
 Data Space Total: 16.32GB
 Data Space Available: 6.133GB
 Metadata Space Used: 2.572MB
 Metadata Space Total: 167.8MB
 Metadata Space Available: 165.2MB
 Thin Pool Minimum Free Space: 1.632GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.146-RHEL7 (2018-01-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.3.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.58GiB
Name: centos-tst01.crt-service
ID: KZOG:YZJD:VOYX:EH4U:3XNZ:JRAS:2BX7:GOIH:HFRM:QFSR:OSUX:BNQC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: alanin
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.21.0, build 5920eb0
docker-py version: 3.2.1
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by marcosbc** [comment]
Hi,

It is unclear to us what you mean by navigating to the page "Test Results on Build". Could you explain how you get to that page?

Thanks!
