### ISSUE TITLE
Problems with PHP threaten when deploy testlink on Cloud Provider

### ISSUE THREAD

**Issue by mayzhou0401** [bitnami/bitnami-docker-testlink#72]
**Description**
I am running the testlink on AWS EC2 machine, but later I receive the threatens from AWS as below:
![image](https://user-images.githubusercontent.com/8501053/45135971-9cffe800-b1d4-11e8-9455-f067c05d7be4.png)

How can I resolve this? otherwise the machine will be shut down.

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
docker version 1.12.6
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

AWS EC2 machine, centos7.4

**Comment by beltran-rubo** [comment]
Hi,

It seems you are using a Windows server in AWS and installed the Bitnami TestLink installer there? Most of the reported issues are DLLs. Others are php scripts that are not included in the mariadb database.  Could you please post what is the exact version you launched?

**Comment by mayzhou0401** [comment]
Hi @beltran-rubo 

Thanks for your quick reply.

I am running testlink container on Ubuntu 16.04.01 LTS, not Windows.
`cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial`

Is this what you want for the question 'Could you please post what is the exact version you launched?' ? 

Feel free to let me know, thanks :)

**Comment by mayzhou0401** [comment]
Yes, I am using the volume under host path.

Yes, those files are all there under mariadb folder.
![image](https://user-images.githubusercontent.com/8501053/45145442-3b02ab00-b1f3-11e8-8c59-4154ee160224.png)

Then, how can I fix this?

**Comment by beltran-rubo** [comment]
I do not know why are those files there. It looks like you are reusing a volume that you used for other containers or similar. 

If you do not have anything else in that machine, I would remove all the volumes and "docker-compose up" of the solution again.

**Comment by mayzhou0401** [comment]
Do you mean initially those files are not there? They are all unused files and not belong to testlink container? So I can remove them directly?

**Comment by beltran-rubo** [comment]
Correct

**Comment by mayzhou0401** [comment]
Hi @beltran-rubo 

Looks like my testlink application was attacked by hackers.
I already clean up the threaten files and it works fine.

Thanks.
