### ISSUE TITLE
How can I access the testlink API when using bitnami testlink?

### ISSUE THREAD

**Issue by mayzhou0401** [bitnami/bitnami-docker-testlink#73]
**Description**

How can I access the testlink API?

**Steps to reproduce the issue:**

I tried to google how to access testlink API and found that the testlink API is below:
`http://{IP or host of testlink server}/testlink/lib/api/xmlrpc/v1/xmlrpc.php`
But this is not working for me.

**Describe the results you received:**

It returns the 404 page not found.
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
AWS EC2 machine, centos7.4

**Comment by beltran-rubo** [comment]
Yes, the API link is correct. Are you able to access the web application? If not check your security groups to open the port 80. What is the error you are getting?

**Comment by beltran-rubo** [comment]
It depends on how the app is configured. In this case the app is installed in the root URL. The correct link for the API is http://IP/lib/api/xmlrpc/v1/xmlrpc.php You should see a message like this "XML-RPC server accepts POST requests only."

I hope it helps

**Comment by mayzhou0401** [comment]
Yes, your link 'http://IP/lib/api/xmlrpc/v1/xmlrpc.php ' is working.

Thanks a lot. 👍

**Comment by mayzhou0401** [comment]
By the way, how can I verify which folder is the root folder for testlink when I access the API?
Actually, I install it on the /home/ubuntu/testlink/ folder.

**Comment by mayzhou0401** [comment]
By using the bitnami testlink image, seems that it always installs on the root folder, so the URL should be the root URL.
