### ISSUE TITLE
DB Access Error after searching keyword on testlink webpage

### ISSUE THREAD

**Issue by sunjundi** [bitnami/bitnami-docker-testlink#75]
**Description**

**Steps to reproduce the issue:**

1. login testlink，and search with some keyword

**Describe the results you received:**
DB Access Error - debug_print_backtrace() OUTPUT START 
 ATTENTION: Enabling more debug info will produce path disclosure weakness (CWE-200) 
            Having this additional Information could be useful for reporting 
            issue to development TEAM.

and I got the following in userlog*.log

Query failed: errorcode[1305]
        errormsg:FUNCTION bitnami_testlink.UDFStripHTMLTags does not exist

**Describe the results you expected:**

will get some search results

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**
- Output of `testlink version`:

```
BITNAMI_IMAGE_VERSION=1.9.17-debian-9-r65
```

- Output of `docker version`:

```
18.06.1-ce
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by tompizmor** [comment]
Hello @sunjundi,

I just tried with a fresh deployment but I cannot reproduce the error. 
Do I have to add some specific content in order to reproduce the issue? Are you able to see this error on a vanilla testlink?

Did you install that version directly or did you upgrade from a previous version?

**Comment by sunjundi** [comment]
> I just tried with a fresh deployment
Hi tompizmor，

I installed mariadb and testlink directly about 2 weeks ago(No upgrade). At that time, testlink version is 1.9.17-debian-9-r65 and mariadb version is 10.1.36-debian-9-r18. Then, I started container and opened webpage, created some testcases, it's OK. 

But when I tried to search, it's failed.

**Comment by tompizmor** [comment]
Hi @sunjundi,

OK! That is what I did but it is working fine for me: Check this screenshot:

![screenshot 2018-10-16 at 13 06 58](https://user-images.githubusercontent.com/4026184/47012481-95711e80-d144-11e8-979a-4a88e6b6bb2a.png)

I don;t know what is the cause of the error but it seems to be an issue in the Teslink application itself. As you can see, the same error has already been reported to them and it is still open in the issue tracker.

http://mantis.testlink.org/view.php?id=8019

Maybe you can ask there if there is any update.

**Comment by shashanknaik1990** [comment]
Hi I am getting 

![image](https://user-images.githubusercontent.com/61155880/100072533-615ba200-2e62-11eb-9bc5-8107855a554a.png)

**Comment by miguelaeh** [comment]
Hi @shashanknaik1990 ,
This is a really old issue, could you open a new one providing as much information as you can please?

**Comment by tim131452** [comment]
> Hi I am getting
> 
> ![image](https://user-images.githubusercontent.com/61155880/100072533-615ba200-2e62-11eb-9bc5-8107855a554a.png)

bro have you found any solutions? im facing the same issue here

**Comment by javsalgar** [comment]
Hi,

Looking at the screenshot, it seems to be an issue with our installers, not our containers. This repository is for issues in containers, for issues in our Cloud Images or Installers please go to community.bitnami.com where our team focused on installers and Cloud Images will be able to help with the issue.
