### ISSUE TITLE
Bug: TestLink Gitlab Create issue failure - generateIssueText() addIssue() missing default value

### ISSUE THREAD

**Issue by Lakshmipathi** [bitnami/bitnami-docker-testlink#76]
**Description**

TestLink fails to create issue on Gitlab-Issue tracker. 

**Steps to reproduce the issue:**

1. After Integrating TestLink to Gitlab, Go to Test Execution page
2. Select a Testcase and click `Create issue` icon.

**Describe the results you received:**

Pop-window appears as  blank. 

**Describe the results you expected:**

Allow TL to add a new issue

**Possible Fix:**
After making below changes on **generateIssueText** -  now I can create issue on gitlab via testlink:

>  /opt/bitnami/testlink/lib/functions/exec.inc.php: 694 needs to be changed

from:

> function generateIssueText($dbHandler,$argsObj,$itsObj,$addLinkToTL) {

to 

> function  generateIssueText($dbHandler,$argsObj,$itsObj,$addLinkToTL=false) {`

Similarly **addIssue**() needs to be changed from 

>`function addIssue($dbHandler,$argsObj,$itsObj,$addLinkToTL)`
to
>`function addIssue($dbHandler,$argsObj,$itsObj,$addLinkToTL=false)`

**Error log:**
[Wed Oct 24 07:41:08.900551 2018] [php7:error] [pid 110] [client 1.215.168.1:4455] 
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function generateIssueText(), 3 passed in /opt/bitnami/testlink/lib/execute/bugAdd.php on line 26 and exactly 4 expected in /opt/bitnami/testlink/lib/functions/exec.inc.php:694\nStack trace:\n#0 /opt/bitnami/testlink/lib/execute/bugAdd.php(26): generateIssueText(Object(database), Object(stdClass), Object(gitlabrestInterface))\n#1 {main}\n  thrown in /opt/bitnami/testlink/lib/functions/exec.inc.php on line 694, referer: http://1.59.15.116/lib/execute/execSetResults.php?version_id=399&level=testcase&id=398&form_token=1345611977&setting_build=39

[Wed Oct 24 07:53:51.718964 2018] [php7:error] [pid 109] [client 1.215.168.1:4669] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function addIssue(), 3 passed in /opt/bitnami/testlink/lib/execute/bugAdd.php on line 36 and 
exactly 4 expected in /opt/bitnami/testlink/lib/functions/exec.inc.php:583\nStack trace:\n#0 /opt/bitnami/testlink/lib/execute/bugAdd.php(36): addIssue(Object(database), Object(stdClass), Object(gitlabrestInterface))\n#1 {main}\n  thrown in /opt/bitnami/testlink/lib/functions/exec.inc.php on line 583, referer: http://1.59.15.116/lib/execute/bugAdd.php?user_action=create&tcversion_id=399&tproject_id=395&tplan_id=396&exec_id=29&tcstep_id=0

**Environment**:
Image created from docker-compose available on bitnami-docker-testlink (as of today)

**Comment by andresbono** [comment]
Hi @Lakshmipathi,

Thanks for submitting this issue and sharing the solution that you have found to your problem. It looks like a TestLink application issue, am I right? Note that this container does not modify the source code of the application, it only packages and configures it to have it running.

Did you share this issue with the TestLink development team?

Regards,
Andrés B.

**Comment by Lakshmipathi** [comment]
Hi Andres, 

Thanks for the response. Got it, will share the details with TestLink devs and hopefully it will get resolved. 

Cheers.
Lakshmipathi.G

**Comment by andresbono** [comment]
Please feel free to open a new issue whenever you need it!
