### ISSUE TITLE
feature request: Upgrade testlink docker image to 1.19.8

### ISSUE THREAD

**Issue by Lakshmipathi** [bitnami/bitnami-docker-testlink#77]
Hi -

All below links use `testlink-1.9.18`

https://bitnami.com/stack/testlink/cloud

https://bitnami.com/stack/testlink/installer

but containers not yet updated. 

https://bitnami.com/stack/testlink/containers

Do you plan to upgrade container image to `1.9.18` or continue using existing `1.9.17` version?

**Comment by andresbono** [comment]
Hi @Lakshmipathi, thanks for letting us know about it. We have not tracked the change in the version for Testlink. We are going to fix it and we will release the latest version (`1.9.18`) as soon as possible. We will update this issue when we have more news.

Thanks again,
-Andrés B.

**Comment by Lakshmipathi** [comment]
thanks @andresbono for looking into this. 

The issue I reported few days  [back](https://github.com/bitnami/bitnami-docker-testlink/issues/76) apparently fixed in 1.9.18 version. (With these two commit-ids `22cde2fbd59a4d184d` and `8086879cbd`) 

Cheers.
Lakshmipathi.G

**Comment by andresbono** [comment]
Hi again @Lakshmipathi, we have just released the latest version of the container:
- [1.9.18-debian-9-r0](https://github.com/bitnami/bitnami-docker-testlink/releases/tag/1.9.18-debian-9-r0)
- [1.9.18-ol-7-r0](https://github.com/bitnami/bitnami-docker-testlink/releases/tag/1.9.18-ol-7-r0)

It is available in https://hub.docker.com/r/bitnami/testlink/tags/ and https://bitnami.com/stack/testlink/containers.

We have also fixed the version tracking issue.

Regards,
-Andrés B.

**Comment by andresbono** [comment]
Hi @Lakshmipathi, we can't reproduce the issue. Are you using the default _docker-compose_?

```
curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-testlink/master/docker-compose.yml > docker-compose.yml
docker-compose up -d
```

If you are using a different one, could you share it with us? Please, if you have sensitive information, substitute it with dummy data.

**Comment by Lakshmipathi** [comment]
Hi @andresbono ,

I'm using docker-compose version. (running this from Digital Ocean one-click app)

> `# docker-compose --version`
> docker-compose version 1.22.0, build f46880fe
> 

Strange,  I tried launching new node and ran above command even there I can't access the site. Though `docker ps ` shows the containers as running.  Let me explore this further. 

Cheers.

**Comment by Lakshmipathi** [comment]
Hey @andresbono -

I suspected something wrong with apache. So I removed that change and used rest of the changes like https://pastebin.com/bPeyV2tt  Now I can access the site!

**Comment by Lakshmipathi** [comment]
Hi @andresbono , If you need more details, please let me know. thanks!

**Comment by andresbono** [comment]
> Hi @andresbono , If you need more details, please let me know. thanks!

@Lakshmipathi, that would be great. No hurries though, if you already solved it!

**Comment by caustico** [comment]
Hello,
I have the same problem with the latest version.
How can I fix this problem?

[Wed Apr 10 10:24:04.289641 2019] [core:notice] [pid 132] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
[Wed Apr 10 10:26:24.462681 2019] [php7:warn] [pid 133] [client 140.0.24.31:16957] PHP Warning:  require(autoload.php): failed to open stream: No such file or directory in /opt/bitnami/testlink/l
ib/functions/email_api.php on line 17, referer: https://140.0.24.33/login.php?viewer=
[Wed Apr 10 10:26:24.462723 2019] [php7:error] [pid 133] [client 140.0.24.31:16957] PHP Fatal error:  require(): Failed opening required 'autoload.php' (include_path='.:/opt/bitnami/php/lib/php:.
:/opt/bitnami/testlink/lib/functions/:/opt/bitnami/testlink/lib/issuetrackerintegration/:/opt/bitnami/testlink/lib/reqmgrsystemintegration/:/opt/bitnami/testlink/third_party/') in /opt/bitnami/te
stlink/lib/functions/email_api.php on line 17, referer: https://140.0.24.33/login.php?viewer=

thanks!

**Comment by andresbono** [comment]
Hi @caustico, in order to reproduce your issue how are you running the container? Are you setting any environment variables or just the default configuration?

What is the specific version of the container that you are running? You can check it by executing:

```
docker run --rm -it THE_CONTAINER_IMAGE_HERE env | grep BITNAMI_IMAGE_VERSION
```

**Comment by caustico** [comment]
Hi @andresbono ,
I'm using docker-compose with this "docker-compose.yml" file:

docker-compose --version
docker-compose version 1.19.0, build 9e633ef

----------docker-compose.yml----------------------
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
    volumes:
      - 'mariadb_data:/bitnami'
  testlink:
    image: 'bitnami/testlink:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'testlink_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      - TESTLINK_USERNAME=admin
      - TESTLINK_PASSWORD=admin
      - TESTLINK_EMAIL=admin@example.com


volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local

-----------------------------------------------------
List of containers and images:
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                      NAMES
5d18bd76d8cc        bitnami/testlink:latest   "/app-entrypoint.sh …"   7 minutes ago       Up 7 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   tl_testlink_1
e6821c2151f8        bitnami/mariadb:latest    "/entrypoint.sh /run…"   7 minutes ago       Up 7 minutes        3306/tcp            

REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
bitnami/testlink    1                   b37a1debc3dc        27 hours ago        372MB
bitnami/testlink    latest              b37a1debc3dc        27 hours ago        372MB
bitnami/mariadb     latest              04f27d7adaa3        2 days ago          261MB
bitnami/testlink    1.9.16              f2ba2837be22        12 months ago       338MB
hello-world         latest              f2a91732366c        16 months ago       1.85kB


docker run --rm -it b37a1debc3dc env | grep BITNAMI_IMAGE_VERSION
BITNAMI_IMAGE_VERSION=1.9.19-debian-9-r66


When I use bitnami/testlink:1.9.16 all work perfect.

Regards,

**Comment by andresbono** [comment]
Hi @caustico, we can reproduce the issue when doing an upgrade from `1.9.16` to `1.9.19`. Is that your case?

Do you have a way to run a clean install of `1.9.19` and migrate the data from the previous version to the new one?

**Comment by caustico** [comment]
Hello @andresbono,

At first I had image 1.9.16 and everything worked fine. Then I updated to the latest version and the last image did not work. (I reported  this error above)

Later, I uninstalled all the images (the latest version and 1.9.16) and I installed the lastest image. I could see that the lastest image was not yet operational (the same error continued).
Finally, I reinstalled the image 1.9.16 and I could verify that this image worked well.

I not have data to migrate from the previous version. I needed the latest image to work with the API of testlink on my test server.

Regards

**Comment by andresbono** [comment]
@caustico, thanks for the explanation.

Are you using docker volumes? In our case, we face your issue when we upgrade to `1.9.19` but keeping the volumes from the previous version of the container. Is it the same for you?

**Comment by caustico** [comment]
Hello @andresbono,

Yes, I'm using docker volumes and I'm keeping the volumes from the previous version of the container. 

I can test  deleting all the containers, volumes and images.

Regards

**Comment by andresbono** [comment]
Thanks for confirming it. We will continue investigating the issue.

**Comment by mcm-gh** [comment]
Hi @andresbono,

I'm experiencing the same problem when trying to upgrade image from 1.9.17 to 1.9.19 while keeping the volumes (don't get a login screen):
`testlink_1  | [Mon Aug 05 13:51:40.240271 2019] [php7:warn] [pid 112] [client 192.168.110.222:54954] PHP Warning:  require(autoload.php): failed to open stream: No such file or directory in /opt/bitnami/testlink/lib/functions/email_api.php on line 17`
Is there a solution/workaround meanwhile?

**Comment by andresbono** [comment]
Hi @mcm-gh, we couldn't find an easy process, but you can try the following:

**IMPORTANT:** Please make sure you do a backup of your data because you may loose it with the process of upgrade.

1. Stop your current deployment

```
docker-compose stop
```

2. Deploy a fresh install of testlink 1.9.19. Wait until it gets initialized and then copy the `bitnami/testlink` folder to your host machine.

```
docker cp -a testlink_1_9_19:/bitnami/testlink /tmp/testlink
```

3. Copy the folder to the original container

```
docker cp -a /tmp/testlink testlink_1_9_17:/bitnami/
```
4. Remove the old container and substitute the image to be `1.9.19`. Start the deployment again

```
docker-compose down
# Modify docker-compose
docker-compose up
```

5. Login to the testlink container and execute the database migrations:

```
mysql -uroot -h mariadb bitnami_testlink < /opt/bitnami/testlink/install/sql/alter_tables/1.9.17/mysql/DB.1.9.17/step1/db_schema_update.sql
mysql -uroot -h mariadb bitnami_testlink < /opt/bitnami/testlink/install/sql/alter_tables/1.9.18/mysql/DB.1.9.18/step1/db_schema_update.sql
mysql -uroot -h mariadb bitnami_testlink < /opt/bitnami/testlink/install/sql/alter_tables/1.9.19/mysql/DB.1.9.19/step1/db_schema_update.sql
mysql -uroot -h mariadb bitnami_testlink < /opt/bitnami/testlink/install/sql/alter_tables/1.9.19/mysql/DB.1.9.19/stepZ/z_final_step.sql
```

**Comment by mcm-gh** [comment]
Thank you for the instructions!
Meanwhile I managed to get it running by restoring DB  by means of a temporary phpmyadmin container & upgrading it's structure the same way.
Your solution looks much more straight forward - will try them soon.

**Comment by andresbono** [comment]
Hi @Lakshmipathi, @caustico, @mcm-gh, just wanted to let you know that we have implemented auto-upgrades between patch versions of the application.
