### ISSUE TITLE
set *_MAXLEN

### ISSUE THREAD

**Issue by montyz** [bitnami/bitnami-docker-testlink#83]
**Description**

I can't figure out the correct way to update these settings:
```
SRS_TITLE_MAXLEN=255
REQ_SPEC_TITLE_MAXLEN=255
TESTCASE_NAME_MAXLEN=255
```

**Steps to reproduce the issue:**

I tried updating `/opt/bitnami/testlink/gui/templates/input_dimensions.conf` but that isn't on a volume so when I restart it gets wiped out.

I also tried updating `cfg/const.inc.php` but wasn't sure if I was updating the right thing?

**Describe the results you received:**

Changes aren't applied.

**Describe the results you expected:**

Just wondering what the right way to make the fields bigger is.

**Comment by andresbono** [comment]
Hi @montyz, can you try mounting the `/opt/bitnami/testlink/gui/templates/input_dimensions.conf` file as a volume? That way, the configuration will be persisted between restarts.
