### ISSUE TITLE
Copy rootfs / failed

### ISSUE THREAD

**Issue by thebpmgroup** [bitnami/bitnami-docker-testlink#88]
**Description**

Step 11/16 : COPY rootfs /
COPY failed: stat /var/lib/docker/tmp/docker-builder802285599/rootfs: no such file or directory

**Steps to reproduce the issue:**

1. [First Step] Create Dockerfile from https://hub.docker.com/r/bitnami/testlink/dockerfile
2. [Second Step] run sudo docker build.

**Describe the results you received:**

Step 11/16 : COPY rootfs /
COPY failed: stat /var/lib/docker/tmp/docker-builder802285599/rootfs: no such file or directory

**Describe the results you expected:**

I expected the dockerfile to build the docker container successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

It is quite annoying :-D

**Version**

- Output of `docker version`:

```
Docker version 18.09.7, build 2d0083d

```

- Output of `docker info`:

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.18.0-25-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.675GiB
Name: locke
ID: LPEO:66YH:7BE3:FDGX:JFKI:ER3U:WRVB:LULC:QEX7:SWA3:3T6Q:NWY6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Physical Ubuntu Desktop 18.04 LTS

**Comment by alemorcuq** [comment]
Hi, @thebpmgroup.

You also need to have the `rootfs` folder, which contain some initialization logic. You can find it here in the repo: https://github.com/bitnami/bitnami-docker-testlink/tree/master/1/debian-9

Just put it in the same folder as your `Dockerfile` and then build again.

Regards,
Alejandro
