### ISSUE TITLE
Not using latest Testlink version when build Dockerfile

### ISSUE THREAD

**Issue by supranov** [bitnami/bitnami-docker-testlink#89]
**This version of Testlink has bug when print document**

**Steps to reproduce the issue:**

described on http://mantis.testlink.org/view.php?id=8556

In your Dockerfile still using "testlink-1.9.19-2", i think it need to be updated to the latest version.

**Comment by carrodher** [comment]
Hi, we're using the latest version published in [GitHub](https://github.com/TestLinkOpenSourceTRMS/testlink-code/releases) and [SourceForge](https://sourceforge.net/projects/testlink/files/TestLink%201.9/), in both cases, the latest one is `1.9.19`.

Please take into account that we are not building images based on upstream nightly releases. As soon as a new version appears in the upstream GitHub releases page or SourceForge, we will build and release a new image using this new version.

We're building the image on a daily basis to include the latest security patches included in the base image (based on Debian), but the application itself we follow the upstream releases cycle.

**Comment by supranov** [comment]
Okay, i see.. Thank you
