### ISSUE TITLE
Volumes not visible on host

### ISSUE THREAD

**Issue by suityou01** [bitnami/bitnami-docker-testlink#92]
**Description**

I have followed the instructions, curled the yml file and started it up. I get a working version of testlink that I am able to log in using a browser on local host. I want to be able to safely backup the database. The volumes specified in the docker-compose file are not visible on the host while the container is running.

**Steps to reproduce the issue:**

1. mkdir testlink
2. cd testlink (note this is in /home/charlie/
3. curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-testlink/master/docker-compose.yml > docker-compose.yml
4. docker-compose up (note my user is a member of the docker group)

container launches and I can successfully log in through the browser using the default credentials.

**Describe the results you expected:**
I would expect the volumes specified in the docker-compose file to be visible in the /home/charlie/testlink folder. All I can see is the docker-compose.yml file.

I am running linux peppermint
My user has rights to create files and folders in the directory listed above

**Version**

- Output of `docker version`:

Docker version 18.09.7, build 2d0083d
- Output of `docker info`:

Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 5.3.0-28-generic
Operating System: Peppermint Ten
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.708GiB
Name: sawyer
ID: URMY:3FXD:4MIT:QP5B:S27A:D5OJ:USI3:WN6U:FUZI:VQZK:GAIL:ETPE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

- Output of `docker-compose version` (if applicable):

docker-compose version 1.17.1, build unknown

**Comment by dani8art** [comment]
Hi @suityou01 

Thank you for open this issue. 

If you are using the default `docker-compose.yml`, it is using named volume that means that the volume is not bound to your local file system, however, you can find them running `docker volume ls`. 

```
DRIVER              VOLUME NAME
local                   testlink_mariadb_data
local                   testlink_testlink_data
```

If you want to do a backup of your data you should use a container like:

```
docker run -ti -v testlink_testlink_data:/bitnami -v $(pwd)/backup:/backup bitnami/minideb tar -cvf /backup/20200131.tar.gz /bitnami
```

On the other hand, you can use bound volume just changing a few lines in the `docker-compose.yml`
```diff
    volumes:
-      - 'mariadb_data:/bitnami'
+      - './mariadb_data:/bitnami'

    volumes:
-    - 'testlink_data:/bitnami'
+    - './testlink_data:/bitnami'

- volumes:
-   mariadb_data:
-     driver: local
-   testlink_data:
-     driver: local
```

Then you the data will be bound to your local file system.

Regards.
