### ISSUE TITLE
Not running on openshift due to root privileges.  Non root container not available. As of Bitnami WordPress container.

### ISSUE THREAD

**Issue by ankitbhtngr** [bitnami/bitnami-docker-testlink#94]
**Description**

**Steps to reproduce the issue:**

1. Install openshift origin 3.11.
2. Install helm 3 on local machine.
3. helm install stable/testlink

test link container not running giving error:
nami    ERROR Cannot find any module matching the provided specification 'apache'

Container should start properly.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by andresbono** [comment]
Hi @ankitbhtngr, the problem appears when the container is executed as non-root user. We support it for some containers, most of them, infrastructure containers such as [MongoDB](https://github.com/bitnami/bitnami-docker-mongodb). But that's not the case of Testlink.

You can make some modifications to our container to be executed as non-root, but we can't ensure it will work. You can see this other issue that might give you an idea of the changes that needs to be done:

https://github.com/bitnami/bitnami-docker-reportserver/issues/1
