### ISSUE TITLE
testlink latest image not running in openshift producing some error while starting the container

### ISSUE THREAD

**Issue by kprasadpn** [bitnami/bitnami-docker-testlink#95]
Hi Bitnami Support Team,

I am trying to deploy testlink latest image in openshift but I am getting below error while runing the container .

Welcome to the Bitnami testlink container
```
--
  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-testlink
  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-testlink/issues
  | Send us your feedback at containers@bitnami.com
  |  
  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
  | INFO  ==> Starting gosu...
  | nami    ERROR Cannot find any module matching the provided specification 'apache'
```

I have tried to run the same image in my laptop using the docker compose file its working perfectly.

Similar issues are producing for images having the tags 1 and 1.9.20-debian-10-r35   .Please suggest a good way to continue from here .

Regards
Krishna Prasad

**Comment by beltran-rubo** [comment]
Hi Krishna,

OpenShift is not supported for TestLink solution right now. OpenShift requires the container to work properly with a random UID and that is not supported by the TestLink container https://cookbook.openshift.org/users-and-role-based-access-control/why-do-my-applications-run-as-a-random-user-id.html 

That is the reason it works properly in your laptop with docker-compose but not in OpenShift. It is also possible to disable this security context constraint in openShift https://docs.openshift.com/container-platform/3.4/admin_guide/manage_scc.html

**Comment by kprasadpn** [comment]
Hi Beltran-rubo,
Thank you for your help , but I can see some K8 Helm charts for deployment so based on that I have created the openshift deployment yamls . 
https://github.com/bitnami/charts/blob/master/bitnami/testlink/templates/deployment.yaml

Could you please help how I can proceed further from this situation ? Any possible ways to continue with deployment in openshift

**Comment by juan131** [comment]
Hi @kprasadpn 

Let's continue the conversation in the new issue you created to avoid confusion and duplicating efforts.
