### ISSUE TITLE
Call to a member function hasRight() on null

### ISSUE THREAD

**Issue by laoshancun** [bitnami/bitnami-docker-testlink#99]
**Description**
There is an Error when edit user info.
```
PHP Fatal error:  Uncaught Error: Call to a member function hasRight() on null in /opt/bitnami/testlink/lib/functions/common.php:1925
Stack trace:
#0 /opt/bitnami/testlink/lib/functions/common.php(1643): getGrantSetWithExit(Object(database), Object(stdClass), Object(testproject), Array)
#1 /opt/bitnami/testlink/lib/usermanagement/userInfo.php(22): initUserEnv(Object(database), Object(stdClass))
#2 {main}\n  thrown in /opt/bitnami/testlink/lib/functions/common.php on line 1925
```
**Steps to reproduce the issue:**
hualvwang:
1. [First Step]
login 
2. [Second Step]
click user edit
**Describe the results you received:**
```
PHP Fatal error:  Uncaught Error: Call to a member function hasRight() on null in /opt/bitnami/testlink/lib/functions/common.php:1925
Stack trace:
#0 /opt/bitnami/testlink/lib/functions/common.php(1643): getGrantSetWithExit(Object(database), Object(stdClass), Object(testproject), Array)
#1 /opt/bitnami/testlink/lib/usermanagement/userInfo.php(22): initUserEnv(Object(database), Object(stdClass))
#2 {main}
  thrown in /opt/bitnami/testlink/lib/functions/common.php on line 1925
```

**Describe the results you expected:**
show edit page

**Additional information you deem important (e.g. issue happens only occasionally):**
this bug was fixed on [TestLinkOpenSourceTRMS](https://github.com/TestLinkOpenSourceTRMS/testlink-code) branch `testlink_1_9_20_fixed`.

**Version**
docker.io/bitnami/testlink:1.9.20-debian-10-r106

**Comment by rafariossaa** [comment]
Hi @laoshancun,
  Thanks for reporting this. 
  In our CD/CI, we track what TestLink team mark as a release, not a individual branch.
  Maybe you can ask testlink team to make a maintenace release with all those fixes that are included in that branch.

**Comment by laoshancun** [comment]
Ok,let me try this.

**Comment by ap0yuv** [comment]
That Bugfix seems to be related to this pull request 256(https://github.com/TestLinkOpenSourceTRMS/testlink-code/pull/256/)

maybe just cherry picking this to release branch would suffice?

**Comment by rafariossaa** [comment]
Hi,
  I am happy you could find a workaround. Thanks for sharing.
  We can not cherry pick from branches, we need a proper tagged release.

**Comment by rafariossaa** [comment]
I am closing this issue.
This should be fixed when a new version of testlink is released.
